### ISSUE TITLE
Crash on Mac OS Sierra

### ISSUE THREAD

**Issue by passereve** [micahflee/onionshare#928] opened 2019-02-28 16:02 UTC
Deleted as duplicate or #927

**Comment by mig5** [comment] 2019-03-01 20:44
Is this not a duplicate of your own issue #927 ?

**Comment by passereve** [comment] 2019-03-01 22:15
Yes it's a mistake on my part.
When I saw it I tried to erase it, but I didn't succeed.
I would like to apologize to you.
--


Le ven. 1 mars 2019 à 21:44, Miguel Jacq <notifications@github.com> a
écrit :

**Closed** 2019-03-11 02:55 UTC
Labels: duplicate
