### ISSUE TITLE
When I use onionshare to host A file, the file size is different sizes on the same page

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#362] opened 2017-02-23 10:38 UTC
When I use onionshare to host A file, the file size is shown in different sizes on the same page. Here is a photo showing the issue. affection onionshare 1.0
location of file I was hosting https://eddie.website/download/?platform=macos&arch=x64&ui=ui&format=portable.tar.gz&version=2.11.15&r=0.6238526655925725
![bug](https://cloud.githubusercontent.com/assets/10781882/23255710/77a7e93a-f971-11e6-9fb6-1e38c76a242a.jpeg)
Here is a photo showing the client while it was hosting the file showing the photo above.
![bug2](https://cloud.githubusercontent.com/assets/10781882/23255772/ab44e72a-f971-11e6-961d-859681536392.jpeg)
Here is another photo showing a much larger difference in size.
![issue2](https://cloud.githubusercontent.com/assets/10781882/23337990/a0ea9196-fbb3-11e6-8ba9-aef88676c19e.jpeg)

**Comment by mig5** [comment] 2017-05-18 08:16
I think that's by design. 

The top file size is the size of the zip file, which has compressed the contents.

The bottom file size is the actual size of the contents inside the zip file.

**Comment by Baccount** [comment] 2017-05-19 04:48
I think it would be helpful if there some type a label next to the file sizes, so that the user knows why they are different sizes

**Comment by mig5** [comment] 2017-05-19 05:47
I've made some changes to the HTML, see this screenshot. @Baccount do you find this to be more clear? (Note that I think it becomes more clear anyway if you are sharing multiple files, as suddenly it looks like a proper list beneath)
<img width="940" alt="screen shot 2017-05-19 at 3 43 29 pm" src="https://cloud.githubusercontent.com/assets/99173/26234752/486e06be-3caa-11e7-8bba-86eccfea116f.png">

PR is at https://github.com/micahflee/onionshare/pull/395

**Comment by Baccount** [comment] 2017-05-20 04:14
That is much more clear, thank you mig5.

**Comment by mig5** [comment] 2017-11-05 22:22
@micahflee this one was fixed in last release and can be closed

**Closed** 2018-01-14 07:28 UTC
