### ISSUE TITLE
Some string clarifications

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#738] opened 2018-09-02 19:17 UTC
When I drag any unreadable file onto Onionshare I get this error `is not a valid file.` instead it should say `This is not a valid file.`
<img width="392" alt="screen shot 2018-09-02 at 12 13 52 pm" src="https://user-images.githubusercontent.com/10781882/44959866-99a1ef00-aeaa-11e8-95c8-8c94d0406b25.png">

**Comment by mig5** [comment] 2018-09-04 01:55
What this underlying issue means is that the string substitution for the filename, is null or empty (presumably due to the readability issue, though this is a surprise, the filename itself should at least be accessible if not its contents).

```
    "not_a_readable_file": "{0:s} is not a readable file.",
```

the `{0:s}` here should contain the value of `filename` from:

```
Alert(self.common, strings._("not_a_readable_file", True).format(filename))
``` 

So we should look at why this is occurring and try to fix the string substitution itself.

How did you create the unreadable file? Can you walk us through the full process that led to the above? I just created a file myself that the user can't read or open, but the string substitution works for me (at least on Linux)

![screenshot_2018-09-04_11-54-22](https://user-images.githubusercontent.com/99173/45005905-735e8980-b039-11e8-8fc1-6d6514801e71.png)

**Comment by Baccount** [comment] 2018-09-04 18:57
@mig5 I do not remember the exact fieldworker I used to produce this bug, I tried multiple hidden files, zero byte files, files with "no access permissions" and locked files. But I'm unable to reproduce the bug. I will keep trying to reproduce this bug.

**Comment by mig5** [comment] 2019-03-18 02:30
@Baccount any luck reproducing this bug? I can't seem to create such an unreadable file.

**Comment by mig5** [comment] 2021-05-03 00:37
I've still never reproduced this. I think we could maybe close it if there's no clear path to reproduce. @micahflee

**Closed** 2021-05-03 20:14 UTC
Labels: bug
