### ISSUE TITLE
incorrect files being hosted

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#428] opened 2017-05-30 02:38 UTC
When I add 4 files and start hosting them and then click the stop hosting, then remove one file and start hosting the files again. The files that are hosted are not he files that I have in onionshare.
Here is a photo showing the bug
![issue](https://cloud.githubusercontent.com/assets/10781882/26566225/5de3aa18-44a6-11e7-9702-463f135d4f44.png)

**Comment by mig5** [comment] 2017-05-30 04:21
Hi @Baccount, thanks for reminding me about this, I saw it the other day too.

I have made a potential fix at https://github.com/micahflee/onionshare/pull/430 - if you are in a position to test it (e.g you are able to build on OS X as per the BUILD.md), that would be great! (No problem if not)

**Comment by mig5** [comment] 2017-05-30 04:44
Actually - confused - my change doesn't do anything, in fact I don't think I reproduce this on master branch anymore?

1) Add 4 files
2) Share
3) Stop Sharing
4) Remove 1 file
5) Start Sharing
6) See only the remaining 3 files in the new share

Strange. Sorry for the confusion, I didn't actually check if I still reproduced this as I recall reproducing it some days ago..

**Comment by Baccount** [comment] 2017-05-30 08:55
I'm currently using 1.1 dev 2 and I'm able to reproduce it every time following the steps that you mentioned above. I'm not sure if this has been fixed in the master branch or not,  I haven't tested it.

**Comment by micahflee** [comment] 2017-05-30 19:49
I'm having trouble reproducing this. I'm using the Mac version of OnionShare 1.1.dev2, just like you. I started OnionShare and added four files:

- `2004-01-27_SIDToday_-_The_Role_of_Technical_Directors_in_AP.pdf`
- `2004-07-01_SIDToday_-_Class_for_Grade_14_and_Above_Denial_and_Deception_Executive_Overview.pdf`
- `2004-07-02_SIDToday_-_A_Patriots_Story.pdf`
- `2004-07-02_SIDToday_-_Making_It_Easy_repost.pdf`

Then I shared it. Here's what it looks like in Tor Browser:

<img width="1092" alt="screen shot 2017-05-30 at 12 47 58 pm" src="https://cloud.githubusercontent.com/assets/156128/26601815/2fe5d92a-4536-11e7-9ffd-aedde34bde5e.png">

Then I stopped the server and deleted `2004-07-02_SIDToday_-_A_Patriots_Story.pdf`, and started it again. Here it is in Tor Browser, and also in OnionShare:

<img width="1092" alt="screen shot 2017-05-30 at 12 48 56 pm" src="https://cloud.githubusercontent.com/assets/156128/26601845/54f180de-4536-11e7-899b-f501b1386616.png">
<img width="540" alt="screen shot 2017-05-30 at 12 49 01 pm" src="https://cloud.githubusercontent.com/assets/156128/26601844/54ee31d6-4536-11e7-8601-b9aa11a2b465.png">

**Comment by Baccount** [comment] 2017-05-30 20:44
I was able to reproduce the bug on my other Mac. I used more than 5 files this time, and I added the files and started the share then stoped the share and deleted one. lastly I started the share and a file is missing. The red arrow is pointing at the file that is not sowing up in Tor Browser.
![issue](https://cloud.githubusercontent.com/assets/10781882/26604010/c578c798-453d-11e7-9606-eebea88093bc.png)

**Comment by Baccount** [comment] 2017-05-30 21:06
I captured a video showing the steps I used to reproduce the bug, and I ran onionshare from terminal.
video link.
http://sendvid.com/gi4ag0u0

**Comment by micahflee** [comment] 2017-05-30 22:01
Strange, I still haven't been able to reproduce it myself, but your video is very compelling. I'll keep trying.

**Comment by mig5** [comment] 2017-05-30 23:09
Even more interesting in https://sendvid.com/1r5iuen0 is that in your second share, you *do* have one less file, but it's 2.rtf that is missing (whereas you removed 4.rtf).

Two separate bugs??

**Comment by mig5** [comment] 2017-05-30 23:23
@Baccount just for getting as much info as possible, can you confirm the actual tarball contains the incorrect contents too or is it just the web page saying so?

**Comment by Baccount** [comment] 2017-05-30 23:26
Here is the zip file that I downloaded from tor browser.
![bug](https://cloud.githubusercontent.com/assets/10781882/26609201/c59a185a-4554-11e7-92bd-bdf27ad1ea5a.png)
[onionshare_o54hps.zip](https://github.com/micahflee/onionshare/files/1039912/onionshare_o54hps.zip)

**Comment by mig5** [comment] 2017-05-30 23:29
Cool - so this zip shows that the *contents* of the zip file are correct (1, 2, 3, 5.rtf)

It is therefore just the web interface that sometimes shows the wrong list - and in the video, specifically has dropped 2.rtf instead of 4.rtf.

Plot thickens!

**Comment by mig5** [comment] 2017-05-30 23:57
*Edit* Although in your screen grab above, you appear not to have reproduced it that time... (your Onionshare GUI and your web page both show the same list of files, which matches the zip)...

**Comment by Baccount** [comment] 2017-05-31 00:03
I followed the same directions that I showed in the video. I did not notice that I did not reproduce it in the screen grab.

**Comment by mig5** [comment] 2017-05-31 00:14
I just reproduced it!

Here's how:

1) Moved the test files (1..5.txt) to my Desktop instead of my home dir
2) Selected them all in a 'drag highlight' from the bottom up to the top (same as is done in the video)
3) Dragged from the top (mouse hovering over 1.txt once all selected) over to Onionshare.

I lose my '2.txt' in the web page even though I deleted 4.txt, and 2.txt is missing from the zip too.

I wonder if this is a combination of Drag+Drop and files being on the Desktop (or at least, being *selected* from the Desktop, rather than from a Finder window.

If I actually drag and drop via a Finder window (after navigating to 'Desktop' in Finder) I don't reproduce it.

I also couldn't reproduce with a Drag + drop of the same files when they are inside my home dir rather than Desktop.

Seems to be a quirk of drag-drop from the *literal* desktop space? @Baccount can you reproduce if the files are inside some other folder and you are dragging from a Finder window?

**Comment by mig5** [comment] 2017-05-31 00:37
It could very well be this bug in Qt on OS X https://stackoverflow.com/questions/27093697/os-x-yosemite-qt-drag-and-drop-file-name-bug

which might require patching Qt, ugh :/

**Comment by mig5** [comment] 2017-05-31 00:43
No, OK: I added some debug logs. When you drag from the actual Desktop, the order of the files is reversed in the list.

When you drag from a Finder window, it's in the right order.

The filenames themselves look OK so it's not the Qt bug above. It's probably just popping the wrong item from the list even though the GUI betrays us otherwise.

Continuing to hack away at it.

**Comment by mig5** [comment] 2017-05-31 01:20
@micahflee fix for this is in https://github.com/micahflee/onionshare/pull/432 - not sure if you wanted to include as part of 1.1?

**Closed** 2017-07-10 02:08 UTC
Labels: bug
