### ISSUE TITLE
I cant unzip file after download

### ISSUE THREAD

**Issue by 0xtrzy** [micahflee/onionshare#1196] opened 2020-09-27 21:43 UTC
```
Archive:  onionshare_2zetcz.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of onionshare_2zetcz.zip or
        onionshare_2zetcz.zip.zip, and cannot find onionshare_2zetcz.zip.ZIP, period.
```

unzip , gzip etc not working
i download default program from fedora (1.3)

**Comment by rossington** [comment] 2021-01-20 09:05
This issue also exists on Debian x86_64 with Onionshare 1.3
I believe the the problem is an incomplete (corrupt) download. See [1198](https://github.com/micahflee/onionshare/issues/1198).
If you wish to attempt to extract the files, use `unar`. Beware that the file integrity may be disrupted.

**Comment by mig5** [comment] 2021-02-03 00:58
Indeed, likely the same issue as https://github.com/micahflee/onionshare/issues/1198 and which has been fixed in the develop branch, awaiting our next release. See my reply in that ticket for other workarounds.

**Closed by mig5** 2021-02-03 00:58 UTC
