### ISSUE TITLE
iframes don't work

### ISSUE THREAD

**Issue by regressmods** [micahflee/onionshare#1104] opened 2020-04-02 00:31 UTC
iframes are unable to render when using the website option.

**Comment by micahflee** [comment] 2020-04-02 00:50
Can you provide an example HTML file? My guess is this has something to do with mixed content -- onionshare websites are http (the encryption is in the onion protocol, not https), so it's possible you'll run into problems if you try including an https iframe.

**Comment by regressmods** [comment] 2020-04-02 01:03
First one
`<html>
<head>
<title>
My little Tor Site v 2
</title>
</head>
<body>
<div>
This is installed welcome to the tor netword, next
<p>Hello there <strong>smile</strong></p>
<br>
<p>Hello there <strong>smile</strong></p>
<iframe src="//7qt3jfi57cebxusqxeuriwyltkk5tl64xixnlfv4diqs5zbgxsksfqqd.onion"></iframe> 
</div>
</body>
</html>`

I also tried www

**Comment by regressmods** [comment] 2020-04-02 01:04
If I was able to update without restarting all the time I wouldn't need a iframe

**Comment by kpcyrd** [comment] 2020-04-02 01:27
iframing onionshare is intentionally blocked for security reasons:

https://github.com/micahflee/onionshare/blob/27107d89928ffd95fcb830b0131911851d982577/onionshare/web/web.py#L108

I'd recommend looking into modern web development, it seems you're trying to implement something in a weird way.

**Comment by regressmods** [comment] 2020-04-02 01:31
I want to be able to update my page without restarting the app every time but I can't so I tried to use a iframe for dynamic content but seems micahflee over looked that lol/

I don't want to create a hole system of hosting this and hosting that the tool says we can host a webpage but having to restart it on every page change even little ones is just nuts I don't know how or why it's cashing the webpage

**Comment by kpcyrd** [comment] 2020-04-02 01:37
an iframe won't help, you're basically asking for #1059 

if you want a dynamic website I'd recommend using nginx instead

**Comment by regressmods** [comment] 2020-04-02 01:40
Look I know how to set stuff like that but the point is been able to update the webpage without restarting the app, there is no reason to lock the file in to the tool we should be able to edit it locally or remotly over the network without restarting the app how I will be doing it 

This is a needed thing for all website serving options cashing makes no sence, I don't want or need to add more resources to the mix when we could ask like I am to have the website part not to be cashed to we can live update. I asking @micahflee to do this as no where does he say you can't update the site without restarting the tool, even his screenshots make it look like he has some kind of wordpress site activly been served so this is NOT my confusen.

**Comment by regressmods** [comment] 2020-04-02 02:04
Without the documentation saying we can't do this, since very other tool does this then you can't blame us for not knowing and I am not going to look back under a 100 posts to see if it was asked I find the way I been dealt with very crappy.

If someone else as also asked for it maybe it's something people wanted.

**Comment by mig5** [comment] 2020-05-23 05:10
As noted, iframes are denied for security purposes. Not likely to be made optional, for UX reasons in the app itself, and because users will shoot themselves in the foot disabling security settings. I know you yourself would not do that, but we have to think of all usersr.

The conversation then derailed into a duplicate of #1059

We'll add documentation to the (https://github.com/micahflee/onionshare/wiki/Website-Mode)[Website Mode] that says files are not dynamically updated until restarted (simply put: a copy is made of the site files into an ephemeral temp area, e.g /tmp on Linux). Yes, could not blame 

I'm not against the idea of serving the files directly to allow for dynamic changing - would indeed be nice - but that's the other ticket, so I'm going to close this one.

Technically, I just noticed it is possible to edit the files being shared, but it is not at all simple. OnionShare makes a copy of the files in /tmp but they are gzipped files and the names are random. Here's my example:

```
user@onionshare:/tmp$ ls -al
total 156
drwxrwxrwt 11 root root  4096 May 23 15:00 .
drwxr-xr-x 20 root root  4096 May  9 22:14 ..
drwxrwxrwt  2 root root  4096 May 23 14:45 .font-unix
drwxrwxrwt  2 root root  4096 May 23 14:45 .ICE-unix
-rw-------  1 user user   902 May 23 14:45 qubes-session-env
-rw-r--r--  1 user user     8 May 23 14:45 qubes-session-waiter
srw-------  1 user user     0 May 23 14:45 .SSH_AGENT_vault
drwx------  2 user user  4096 May 23 14:45 ssh-evbW4NUzUpxN
drwx------  3 root root  4096 May 23 14:45 systemd-private-2a39a59b7352496aa5ea96888653a56d-haveged.service-s2asaR
drwx------  3 root root  4096 May 23 14:45 systemd-private-2a39a59b7352496aa5ea96888653a56d-rtkit-daemon.service-QQgZXw
drwx------  3 root root  4096 May 23 14:45 systemd-private-2a39a59b7352496aa5ea96888653a56d-tor@default.service-YYR8PV
drwxrwxrwt  2 root root  4096 May 23 14:45 .Test-unix
-rw-------  1 user user 11707 May 23 14:59 tmp05xqklrgwb+
-rw-------  1 user user  2247 May 23 14:59 tmp7rq2gfgtwb+
-rw-------  1 user user 15814 May 23 14:59 tmpal774r16wb+
-rw-------  1 user user 10889 May 23 14:59 tmpf9j0a5z1wb+
-rw-------  1 user user  6343 May 23 14:59 tmpjbgeogk3wb+
-rw-------  1 user user  5944 May 23 14:59 tmp_jo68qhswb+
-rw-------  1 user user  1636 May 23 15:00 tmpjpuk877owb+
-rw-------  1 user user   895 May 23 14:59 tmpslwieh68wb+
-rw-------  1 user user   630 May 23 14:59 tmpu_5hwn7_wb+
-rw-------  1 user user 14291 May 23 14:59 tmpucel6w8swb+
-rw-------  1 user user  3599 May 23 14:59 tmpxr6hi7_jwb+
-rw-------  1 user user  2320 May 23 14:59 tmpydf7xwtnwb+
-rw-------  1 user user  1603 May 23 14:59 tmpyjx_31l0wb+
-r--r--r--  1 user user    11 May 23 14:45 .X0-lock
```

I was able to zgrep for a specific bit of content in these, to find the file I wanted to edit.

Then I had to rename the file to have a `.gz` extension, so I could gunzip it, and then edit the file, then re-gzip it:

```
user@onionshare:/tmp$ mv tmp7rq2gfgtwb+ tmp7rq2gfgtwb+.tar.gz
user@onionshare:/tmp$ gun^C
user@onionshare:/tmp$ mv tmp7rq2gfgtwb+.tar.gz tmp7rq2gfgtwb+.gz
user@onionshare:/tmp$ gunzip tmp7rq2gfgtwb+.gz
user@onionshare:/tmp$ vim tmp7rq2gfgtwb+ 
user@onionshare:/tmp$ gzip tmp7rq2gfgtwb+
```

After that, the changes were visible in the onion address without having to stop/start.

No, this is not at all practical. But possible. In the other ticket, we may see if we can avoid copying the files to the temp area to begin with.

> even his screenshots make it look like he has some kind of wordpress site activly been served so this is NOT my confusen.

Not a Wordpress site. Static HTML generated site.

**Closed by mig5** 2020-05-23 05:10 UTC
