### ISSUE TITLE
The Installer should ask the user where he wants to install OnionShare to

### ISSUE THREAD

**Issue by computerfreak94** [micahflee/onionshare#1300] opened 2021-02-26 10:28 UTC
OS: `Windows 10 Home 1909`
Version: `OnionShare 2.3.1`

Currently the installer installs OnionShare to a location the user can not choose.

This makes it difficult for people who would like to keep their C:\ drive as clean as possible.

Giving the user the option to decide where OnionShare should install itself to could maybe also make it possible to use it in a "portable lite" way if the user decides to install it onto a removable media to use it at different computers.

**Comment by mig5** [comment] 2021-02-28 22:18
Duplicate of https://github.com/micahflee/onionshare/issues/367 (and related #366)

**Closed by mig5** 2021-02-28 22:18 UTC
