### ISSUE TITLE
public mode and persistent addess is broken

### ISSUE THREAD

**Issue by speedtester** [micahflee/onionshare#835] opened 2018-12-08 21:35 UTC
Hi,
Public mode removes and disables the slug, and therefore the download link is not working (still pointing to a link with a slug), gives error 404.
Manually adding /download to the url works.
Also persistent address is not working (neither in receive-mode), only the slug remains the same.

![screenshot_2018-12-08_onionshare_settings](https://user-images.githubusercontent.com/45670611/49690930-95801000-fb30-11e8-8cc7-7e67a2fd2ac0.png)
![screenshot_2018-12-08_onionshare](https://user-images.githubusercontent.com/45670611/49690931-9618a680-fb30-11e8-99d3-40da7459afa0.png)

**Comment by mig5** [comment] 2018-12-09 22:36
Hi @speedtester ,

Are you definitely using the latest code from the `develop` branch? 

I ask because this was definitely a bug, but it was fixed in #765 back in September.

I don't reproduce this in the current `develop` branch. 

Maybe you need to `git pull origin develop` and try again?

**Comment by speedtester** [comment] 2018-12-10 09:51
Hi @mig5 ,
It says: Already up-to-date.

**Comment by mig5** [comment] 2018-12-11 05:36
Hi @speedtester, can you show the output of these commands?

```
git branch
```

```
git remote -v
```

**Comment by speedtester** [comment] 2018-12-11 15:48
user@host:~/onionshare$ git branch
* develop
user@host:~/onionshare$ git remote -v
origin  https://github.com/micahflee/onionshare.git (fetch)
origin  https://github.com/micahflee/onionshare.git (push)

**Comment by mig5** [comment] 2018-12-11 21:09
Hmm, well I just don't reproduce this on the same branch and repo. I'll leave to @micahflee to see if he does.

**Comment by mig5** [comment] 2018-12-12 21:43
@speedtester, if you do a `git clone --develop https://github.com/micahflee/onionshare onionshare_temp`, then cd into `onionshare_temp` and run `dev_scripts/onionshare-gui` do you reproduce the issue in this new copy of OnionShare?

**Comment by speedtester** [comment] 2018-12-13 13:53
@mig5, 
`user@host:~$ git clone --branch develop https://github.com/micahflee/onionshare onionshare_temp
Cloning into 'onionshare_temp'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 11110 (delta 1), reused 7 (delta 1), pack-reused 11093
Receiving objects: 100% (11110/11110), 6.98 MiB | 877.00 KiB/s, done.
Resolving deltas: 100% (7809/7809), done.
`
Here is the way to reproduce error:
I've started it immediately with defaul settings: public mode and persistent address,  ticked.
It gave me a fully working url without slug.
Then I disabled public and shared again, it came with a slug, but with a new url.
Reenabled public mode and share gave a new url again without slug.
Disabled persistent and legacy and turned public on and hit share.
It gave me a v3 url without slug, having download button with a slug link giving 404.
Manually adding /download to the address bar works.

**Comment by micahflee** [comment] 2018-12-17 02:42
Hey @speedtester thanks for submitting this. I'm able to reproduce in the `develop` branch on my Mac. In settings, I enabled public mode and persistent address.

Then I shared a file, and got this address: http://gneodxm4kyvqnram.onion/. When loading it, the download link linked to this: http://gneodxm4kyvqnram.onion/raft-willfully/download. I then stopped it and started the share again, and got a different address: http://nqszezyrwklipxb2.onion. Then I stopped it and opened the settings dialog, and, strangely, public mode and persistent address were unchecked.

I checked them and saved, then closed OnionShare and opened it again. They were still checked. But this time, for some really weird reason, I can't reproduce it a second time.

I think this might be a tricky and inconsistent bug related to what settings are being used or how they're being saved or something, and not actually a bug related to the the public mode/persistent address features. I'll try to see if I can more consistently reproduce it...

**Comment by micahflee** [comment] 2018-12-17 02:48
And now I can't reproduce it... weird, I indeed did reproduce it the first time I tried. Since it's so difficult to reproduce, I'm removing the 2.0 milestone.

**Comment by mig5** [comment] 2018-12-17 02:50
>  Then I stopped it and opened the settings dialog, and, strangely, public mode and persistent address were unchecked.

Theory on this: on a Mac, your Update Thread ran with the original settings prior to you changing them. You then changed your settings and saved. Then the UpdateThread completed, and re-saved your settings.json (with the new 'last checked for update' timestamp), but with the original other settings, in effect undoing your changes.

Just a theory.

Of course, I think the original poster is on Qubes, so that won't be the case there.

**Comment by speedtester** [comment] 2018-12-17 10:31
> Then I stopped it and opened the settings dialog, and, strangely, public mode and persistent address were unchecked.

I can't remember experiencing this.

> And  now I can't reproduce it... weird, I indeed did reproduce it the first time I tried. Since it's so difficult to reproduce, I'm removing the 2.0 milestone.
Shall I share my onionshare appvm backup? This bug is constantly reproducible.

Or I can check settings.json content, or whatever helps finding the cause.

**Comment by speedtester** [comment] 2018-12-18 15:51
here it is:
`{"private_key": "", "use_stealth": false, "save_private_key": false, "downloads_dir": "/home/user/OnionShare", "no_bridges": true, "autoupdate_timestamp": null, "tor_bridges_use_obfs4": false, "close_after_first_download": false, "socket_file_path": "/var/run/tor/control", "public_mode": true, "tor_bridges_use_meek_lite_azure": false, "version": "2.0.dev", "socks_port": 9050, "auth_password": "", "use_autoupdate": true, "tor_bridges_use_custom_bridges": "", "shutdown_timeout": false, "connection_type": "automatic", "control_port_address": "127.0.0.1", "slug": "", "hidservauth_string": "", "control_port_port": 9051, "auth_type": "no_auth", "locale": "en", "socks_address": "127.0.0.1", "use_legacy_v2_onions": false}`

**Closed** 2019-02-18 22:14 UTC
Labels: bug
