### ISSUE TITLE
Onionshare crashes when my friend opens the link

### ISSUE THREAD

**Issue by tristan-yc** [micahflee/onionshare#1198] opened 2020-10-01 13:18 UTC
I upload a file to Onionshare, send the link to my friend, he opens it in Tor, I see it in the sent menu in the app, but then the app just closes and my friend can't complete the download.

**Comment by tyhp** [comment] 2020-10-24 15:10
What version of Onionshare are you using and on what operating system?

**Comment by rossington** [comment] 2021-01-20 09:05
This issue exists on Debian x86_64 with Onionshare 1.3 cli.
The symptoms are the same as [1255](https://github.com/micahflee/onionshare/issues/1255), excluding the timer usage.
The download prematurely stops when the upload is complete, resulting in an incomplete (corrupt) download, e.g. [1196](https://github.com/micahflee/onionshare/issues/1196).
The current work around is to use the `--stay-open` option, and kill the instance manually after confirmation of successful download.

**Comment by mig5** [comment] 2021-02-03 00:58
Hi,

I believe this bug is fixed in the develop branch, and will therefore be fixed in our upcoming 2.3 release. Please see the pull request https://github.com/micahflee/onionshare/pull/1236 where the issue is described and fixed.

I recommend either:

a) using the 'stay open' method as described, as a stopgap solution, or
b) building from the 'develop' branch if you want to try the upcoming release, where this issue's fixed, or
c) wait for the OnionShare 2.3 (coming Real Soon Now a.k.a When It's Ready :) )

Thanks and sorry for the inconvenience!

**Closed by mig5** 2021-02-03 00:58 UTC
