### ISSUE TITLE
Segfault when zipping 1.5G video file

### ISSUE THREAD

**Issue by yawnbox** [micahflee/onionshare#231] opened 2015-12-06 07:33 UTC
When using the GUI. Using the CLI does not cause this crash.

cat kern.log |grep onion

kernel: [101741.563036] onionshare-gui[23325]: segfault at 148 ip 00007f00cb12b155 sp 00007f0099d4ae30 error 4 in libQtGui.so.4.8.6[7f00cae07000+aa9000]

Ubuntu 15.10 desktop x64

**Comment by yawnbox** [comment] 2015-12-06 07:40
Reproduced with a 1.1G ISO.

**Comment by micahflee** [comment] 2015-12-06 22:09
I just shared a 1GB file with both the CLI and GUI, in a Debian Jessie VM in Qubes, so I haven't been able to reproduce it yet. I'll try reproducing in Ubuntu 15.10 next.

**Comment by micahflee** [comment] 2015-12-06 22:28
I can't reproduce in an Ubuntu 15.10 VM, it just seems to work fine. Is it possible that your computer is running low on memory?

**Comment by yawnbox** [comment] 2015-12-07 01:58
I am not low on memory, but it could be unique to my system. I can reinstall the OS and try again to confirm.

**Comment by micahflee** [comment] 2015-12-08 00:25
Removing the 0.8.1 milestone, but I'll keep this open for now in case I can figure out how to reproduce in the future.

**Comment by freddymartinez9** [comment] 2016-05-14 15:36
couldn't reproduce on Fedora 22. I can try on Debian, but I do notice that is a QT crash. I'm wondering if its related to the use of Unity or Cinnamon in mint or ubuntu.

**Comment by mig5** [comment] 2019-03-18 02:41
I can't reproduce this on Ubuntu 18.04 with OnionShare 2. Maybe it was fixed as part of upgrade to Qt5 some years back. I'm gonna close this but we can reopen if someone else still reproduces it on a more modern version.

**Closed by mig5** 2019-03-18 02:41 UTC
Labels: bug
