### ISSUE TITLE
Resize OnionShare window not possible

### ISSUE THREAD

**Issue by computerfreak94** [micahflee/onionshare#1299] opened 2021-02-26 10:18 UTC
OS: `Windows 10 Home 1909`
Version: `OnionShare 2.3.1`

When starting OnionShare the bottom part of OnionShare is hidden behind my taskbar at the bottom of the screen so i dont see the settings button.
Trying to shrink the window by clicking and holding at the top bar of the OnionShare window and hovering it down does not work.

Putting it on fullscreen makes it possible to access the settings button but i think it could be good to be able to resize the window as needed.

**Comment by mig5** [comment] 2021-02-28 22:16
I think this is effectively a duplicate of https://github.com/micahflee/onionshare/issues/1091

**Closed by mig5** 2021-02-28 22:16 UTC
