### ISSUE TITLE
Feature Request - Authorization cookie

### ISSUE THREAD

**Issue by Taz776** [micahflee/onionshare#1313] opened 2021-03-05 17:46 UTC
https://www.void.gr/kargig/blog/2015/04/10/onion-service-authorization-cookie/

With a simple checkbox activation.

**Comment by micahflee** [comment] 2021-04-11 18:59
This actually is already supported but only for v2 onion services. If you choose "View advanced settings", check "Use a legacy address", you can then check "Use client authorization". With v3 onion services the way this works has totally changed, and it's not supported yet.

Marking this as a duplicate of https://github.com/micahflee/onionshare/issues/697

**Closed by micahflee** 2021-04-11 18:59 UTC
Labels: duplicate
