### ISSUE TITLE
[Feature request] Windows settings request aka "portable" version

### ISSUE THREAD

**Issue by vatterspun** [micahflee/onionshare#378] opened 2017-04-15 20:04 UTC
Had a suggestion that I think some users might enjoy ...

**Current behavior**

The program currently writes settings to _\AppData\Roaming\OnionShare\onionshare.json_

**Requested behavior**

Optionally write all program settings to the local folder.  This would make it easier to protect user privacy and allow it to be run from a cloud service or USB drive.

**Ideal behavior**

The program writing *nothing* outside the OnionShare program would be even better.  I haven't run a thorough test on an available Windows machine to see if this is the case, I only know about the AppData save.

---

Thanks for your work on this program.  There are a lot of great Tor programs but very few of them allow for file exchange.

**Comment by mig5** [comment] 2017-05-29 05:20
Duplicate of #366

**Comment by vatterspun** [comment] 2017-05-29 23:39
My apologies.  I had on my list to put in a request for this feature and I evidently didn't take it off my list after the first submission.  Please feel free to delete the duplicate.  I'm not trying to spam the topic.

**Comment by mig5** [comment] 2017-11-05 22:22
@micahflee this one can be closed

**Closed** 2017-11-06 04:05 UTC
