### ISSUE TITLE
onionshare-gui not working in Tails 3.12

### ISSUE THREAD

**Issue by scootergrisen** [micahflee/onionshare#891] opened 2019-01-29 22:25 UTC
onionshare-gui command does not work in latest Tails (tails-amd64-3.12.iso).
![onionshare-gui](https://user-images.githubusercontent.com/1836590/51944109-7a889880-241b-11e9-9d82-eac34cc3d0cb.jpg)

onionshare commando says version 0.9.2.

Could it be incorrect Python version perhaps? 2 instead of 3 or the other way.

**Comment by emmapeel2** [comment] 2019-01-31 12:36
I can run onionshare in Tails 3.12 with onionshare-gui, and also right-clicking on a file (located in the ~/Tor Browser/ folder).

I am not sure why you get that error. It looks like a problem with the graphic card...

**Comment by scootergrisen** [comment] 2019-01-31 20:17
I test in VirtualBox Version 6.0.0 r127566 (Qt5.6.2).

onionshare-gui (0.9.2) will not start with:
Graphics controller VBoxVGA with 3D acceleration on.

onionshare-gui (0.9.2) starts with:
Graphics controller VBoxSVGA or VMSVGA with 3D acceleration on.

vboxsvga_3d_on
![vboxsvga_3d_on](https://user-images.githubusercontent.com/1836590/52082008-f6115380-259b-11e9-9787-6425584f61a8.jpg)

vmsvga_3d_on
![vmsvga_3d_on](https://user-images.githubusercontent.com/1836590/52082052-0de8d780-259c-11e9-9f62-2399ef7b0f95.jpg)

I just dont see why a program like onionshare would want to retrice device information and load graphics driver and do MESA stuff.

There also seem to be at least one another program openpgp-applet that does not seem to start in Tails with VBoxVGA with 3D acceleration on so onionshare-gui is not the only one.

Trying to run openpgp-applet gives:

    (openpgp-applet:324): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

I dont know how to try the latest onionshare verion.
Are there some easy way to do that in Tails?

**Comment by emmapeel2** [comment] 2019-01-31 21:42
I suggest we move this discussion to a Tails ticket.

> process 7958: D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/etc/machine-id": Permiso denegado
> See the manual page for dbus-uuidgen to correct this issue.
> process 7958: D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/etc/machine-id": Permiso denegado
> See the manual page for dbus-uuidgen to correct this issue.
> Qt: Session management error: None of the authentication protocols specified are supported
> libGL error: MESA-LOADER: failed to retrieve device information
> libGL error: Version 4 or later of flush extension not found
> libGL error: failed to load driver: i915
> libGL error: MESA-LOADER: failed to retrieve device information

Apparently this errors are due to AppArmour.

**Comment by emmapeel2** [comment] 2019-01-31 21:42
@scootergrisen could you please start Tails, reproduce this problem, and send a WhisperBack report?

**Comment by scootergrisen** [comment] 2019-01-31 22:36
I created https://redmine.tails.boum.org/code/issues/16414
I tried WhisperBack report but did not work but now i see network was disabled so thats properly why.
... tried enabled network and send but says "PySocks doesn't support IPv6".

**Comment by micahflee** [comment] 2019-02-10 05:14
Thanks @emmapeel2 and @scootergrisen. Since this is being handled on the Tails side I'm going to close this issue.

**Closed by micahflee** 2019-02-10 05:14 UTC
