### ISSUE TITLE
Crash when clicking stop sharing

### ISSUE THREAD

**Issue by Jackiam** [micahflee/onionshare#331] opened 2016-12-25 00:47 UTC
The app will crash when you click stop sharing after tor browser been closed. I made a video showing the steps to cause the crash.
[Crash.zip](https://github.com/micahflee/onionshare/files/672010/Crash.zip)

**Comment by micahflee** [comment] 2016-12-26 03:59
This is a duplicate of #324, and in fact it's already been fixed and merged into master. So this should no longer happen in the next version that gets released.

**Closed by micahflee** 2016-12-26 03:59 UTC
Labels: duplicate
