### ISSUE TITLE
meek_lite not supported in the obfs4proxy binary shipped with Tor Browser

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#647] opened 2018-02-26 00:26 UTC
I get stuck at connecting to directory server when using amazon meek lite.
`Connecting to the Tor network: 5% - Connecting to directory server`
tested using the latest develop build.

**Comment by mig5** [comment] 2018-02-26 00:29
It works for me on Linux, but I noticed this on Windows too yesterday.

I'm not sure it's OnionShare..

**Comment by mig5** [comment] 2018-02-26 00:36
Yeah I reproduce it on macOS too :/

**Comment by mig5** [comment] 2018-02-26 00:41
Ah.

I ran tor from CLI with a custom torrc using the same meek lite settings and I saw this Tor message

```
Client managed proxy encountered a method error. (meek_lite no such transport is supported)
```

So indeed, I guess the obfs4proxy binary that ships with Tor Browser doesn't support meek :/ what to do?

**Comment by Baccount** [comment] 2018-02-26 00:48
meek-client and meek-client-torbrowser are both included in Tor browser. TorBrowser.app/Contents/MacOS/Tor/PluggableTransports

**Comment by mig5** [comment] 2018-02-26 01:23
I will try and do some tests but my concern is whether those binaries support meek_lite (not just main meek)

**Comment by mig5** [comment] 2018-02-26 01:26
Yeah similar error with meek-client (meek_lite no such method')

**Comment by micahflee** [comment] 2018-02-26 01:58
Confirmed, I'm not able to connect to meek_lite Amazon in macOS.

**Comment by mig5** [comment] 2018-02-26 02:20
meek_lite was introduced to obfs4proxy in v.0.0.6, back in 2016: https://github.com/Yawning/obfs4/blob/obfs4proxy-0.0.6/ChangeLog

On Fedora I have v0.0.7 so that's why it's working.

The version bundled with Tor Browser on Mac (and probably same on Windows) is for some reason super old! v0.0.5, so it predates the meek_lite feature.

**Comment by mig5** [comment] 2018-02-26 02:30
Created https://trac.torproject.org/projects/tor/ticket/25356#ticket

**Comment by micahflee** [comment] 2018-02-26 17:59
Marking this blocked until Tor Browser starts shipping more up-to-date obfs4proxy binaries.

**Comment by mig5** [comment] 2018-02-27 04:24
The updated binary should arrive in the 'alpha' Tor Browser channel in about 2 weeks. We can always choose to download both binaries and extract the obfs4proxy from alpha, tor binary from stable. Or we can just wait til it lands in stable, but that might take a lot longer.

**Comment by Baccount** [comment] 2018-03-02 21:53
@mig5 The latest TorBorwser nightly should include obfs4proxy in v0.0.7 
https://nightlies.tbb.torproject.org/tor-browser-builds/2018-03-01/nightly-osx-x86_64/TorBrowser-tbb-nightly-osx64_en-US.dmg

**Comment by Baccount** [comment] 2018-03-13 19:22
After #647 is merged this would no longer be blocked on macOS and windows.

**Comment by pouyamiralayi** [comment] 2018-06-17 02:01
Hi!
I have downloaded tbb (8.0a8) for windows and used the obfs4proxy binary provided there. but still have issue using a meek pt. 
my question is that am i using the correct binary version of obfs4proxy for this?

**Comment by Baccount** [comment] 2018-06-17 04:38
@pouyamiralayi Remember only use meek pluggable transport if it is absolutely necessary because the cost torproject for every GB you transfer, if obsf4 is not blocked then you should use that instead. All you need to do is open torbrowser click the Onion icon and click `Tor Network settings ` and click the checkbox `Tor is censored in my country` and select a bridge meek-azure and click ok. Then open onionshare and click settings and check attempt to automatically configure with TorBrowser and it should not bootstrap using meek.

**Comment by pouyamiralayi** [comment] 2018-06-17 05:12
@Baccount
according to this [https://github.com/micahflee/onionshare/pull/674](url) ,
i think i found the magic that make most of the users unable to use meek from obfs4proxy binary:
when you specify your ClientTransport in the torrc file, you must set the type as meek not obfs4:
`ClientTransportPlugin meek exec TorBrowser\Tor\PluggableTransports\obfs4proxy `

**Comment by pouyamiralayi** [comment] 2018-06-17 05:16
@Baccount
you are totally right about the expense of using meek.
my situation differs from the normal user, i am developing on the tor for making some customizations.
thank you for your support.

**Comment by Baccount** [comment] 2018-06-17 07:56
@pouyamiralayi I Know about that [thread](https://github.com/micahflee/onionshare/pull/674) I just provided directions on the easiest way to use meek without having to change any code. Version 2.0 of onionshare should have meek built in.

**Comment by mig5** [comment] 2019-03-11 05:55
This works fine for me on MacOS now with the Azure meek_lite bridges, since the version of obfs4proxy fetched from Tor Browser in our bundle is newer these days.

I think we can close this.

**Closed by mig5** 2019-03-11 05:55 UTC
Labels: blocked, bug
