### ISSUE TITLE
Should Onionshare automatically connect to Tor on a fresh install?

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#937] opened 2019-03-08 06:16 UTC
A user on blog.torproject.org brought up a good point, should Onionshare automatically connect to Tor on a fresh install?
> Does it really connect immediately without prompting? Doesn't that potentially flag your traffic for using public Tor relays? Wouldn't it be safer to start by asking if you want to connect or configure similar to what a new Tor Browser install does?
https://blog.torproject.org/comment/280145#comment-280145

**Comment by mig5** [comment] 2019-03-08 06:31
It's probably a duplicate of #436 - it would be good to get some contributions for that onboarding feature

**Comment by micahflee** [comment] 2019-03-11 02:54
Yeah this is a duplicate of #436 -- but still, a good idea to implement.

**Closed by micahflee** 2019-03-11 02:54 UTC
Labels: duplicate
