### ISSUE TITLE
OnionShare could not connect to Tor: utf-8

### ISSUE THREAD

**Issue by JMLatGitHub** [micahflee/onionshare#1294] opened 2021-02-23 12:52 UTC
Hi there

Installed OnionShare for the first time, but application can’t connect to Tor network using the built-in Tor version.

![grafik](https://user-images.githubusercontent.com/3677204/108845637-f5faab00-75dd-11eb-9cf4-7b3ba2b90f13.png)

My setup:
OnionShare V2.3.1
Windows Edition: Windows 10 Home
Windows Version: 20H2
Windows OS build: 19042.804
Windows Experience: Windows Feature Experience Pack 120.2212.551.0
Tor browser NOT installed.

![grafik](https://user-images.githubusercontent.com/3677204/108845892-42de8180-75de-11eb-8404-5731c6631bc6.png)

Any hint what the problem could be? Strangely enough, did not find similar failures/issues reported here at GH or by google’ing...

Tx in advance.
JML

**Comment by Alexound** [comment] 2021-02-25 20:08
@JMLatGitHub
Hey there.

Could you try the different way to connect to tor, i.e. with tor built-in into Tor Browser?
You'll need to install Tor Browser first: https://www.torproject.org/download/

In case it won't work, you'll need to install console version of the OnionShare - 'onionshare-cli' - to get debugging output.
Don't worry, I'll provide you with step-by-step instructions how to do that.

Regards,
Alexound.

**Comment by JMLatGitHub** [comment] 2021-02-25 23:48
Hi Alexound

I'd install Tor browser and started it. On the OnionShare side, I changed the connection option from "Use the Tor version built into OnionShare" to "Attempt auto-configuration with Tor Browser". Now I'm getting the following error message: Could not connect to the Tor controller.

![grafik](https://user-images.githubusercontent.com/3677204/109231678-4f71fe00-77c7-11eb-8753-5d91c9a2e833.png)

Besides that, I installed OnionShare on the same system, but under another user account. Here I could start OnionShare without facing issues, not testing till now any kind of functionality (e.g. sharing or receiving files) though. OnionShare at this time is configured to use built in Tor browser and official Tor browser isn't installed under that user. Currently, I have no clue what the differences between the two user accounts could be, the failing one is my personal account, the working one is a user that I use for testing purposes.

Regards,
JML

**Comment by Alexound** [comment] 2021-02-26 16:04
@JMLatGitHub
Okay, this is what you need to do:

1. First, you need to install Python for Windows. Here the [link](https://www.python.org/downloads/release/python-392/) to the download page. You will find installer at the bottom of page:
![image](https://user-images.githubusercontent.com/22021219/109320757-d1b2fe80-7869-11eb-90ee-72695eb4ea39.png)

2. During the installation, make sure, that you add Python to PATH:
![image](https://user-images.githubusercontent.com/22021219/109321260-5ef65300-786a-11eb-8300-1266576fa593.png)

3. After installation is complete, run PowerShell as administrator and run the following command:
`python3 -m pip install pip --upgrade --user`
This will upgrade 'pip' (package installer for python) module to the latest version.

4. Next, you need install 'onionshare-cli' package to be able retrieve debugging output. To do so, run this command in your PowerShell console:
`python3 -m pip install onionshare-cli --user`

5.1 Now try to run this command:
`./onionshare-cli --verbose --receive`
It will produce a lot of output, and in case error pops up, you'll be able to identify it. Please, make a screenshot of what you see and paste it here.

5.2 Also, you can try to run this command:
`./onionshare-cli --verbose --receive | Tee-Object 'debug.txt'`
It will save all the output to the file named 'debug.txt', so you can attach it here.

That should be it.
Feel free to ask any questions.

Regards,
Alexound.

**Comment by JMLatGitHub** [comment] 2021-02-27 01:20
Hi Alexound

Well, I installed Python as described with my non-privileged user (that one, where OnionShare isn't working). Then I had to start the PowerShell under that user (because admin user did not have the correct env settings) and also running `python` instead of `python3`.

The installation of 'onionshare-cli' went apparently well,

![grafik](https://user-images.githubusercontent.com/3677204/109369984-dfcf4200-789e-11eb-9d87-8027a45eed23.png)

but at the end of the process I got some warnings:

`  WARNING: The script flask.exe is installed in 'C:\Users\User containing é, í, ó and spaces in his name\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.`
`  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.`
`  WARNING: The script chardetect.exe is installed in 'C:\Users\User containing é, í, ó and spaces in his name\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.`
`  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.`
`  WARNING: The script unidecode.exe is installed in 'C:\Users\User containing é, í, ó and spaces in his name\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.`
`  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.`
`    Running setup.py install for stem ... done`
`  WARNING: The script onionshare-cli.exe is installed in 'C:\Users\User containing é, í, ó and spaces in his name\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.`
`  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.`

Checking the PowerShell path env, I can't find anything obbiously missing (did substitute my username with a sample):

`[System.Environment]::GetEnvironmentVariable("Path")`
`C:\Program Files (x86)\VMware\VMware Player\bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\ojdkbuild\java-12-openjdk-12.0.2-1\bin;C:\Program Files\PuTTY\;C:\Program Files\WireGuard\;C:\Users\User containing é, í, ó and spaces in his name\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\User containing é, í, ó and spaces in his name\AppData\Local\Programs\Python\Python39\;C:\Users\User containing é, í, ó and spaces in his name\AppData\Local\Microsoft\WindowsApps`

Executing `onionshare-cli --verbose --receive` I'm getting the following error:

![grafik](https://user-images.githubusercontent.com/3677204/109369292-253e4000-789c-11eb-877f-a41fdf111f9c.png)

A folder structure `OnionShare\app_packages\onionshare_cli` is in place, but I can't find a file called `onionshare-cli`...

Kind regards,
JML

**Comment by Alexound** [comment] 2021-03-01 18:15
@JMLatGitHub 
Greetings.
It seems like the problem is now obvious. 

I suppose you're familiar with the concept of environmental variables.
One of the is `$env:path` which contains the absolute address of the directory with the executable files.

In your case, it looks like an 'egg and chicken' problem':
1. The name of your user contains symbols 'é, í, ó`
2. Path to the directory containing scripts, which can encode those symbols as UTF-8, contains those symbols.
3. So, the directory containing those scripts is not included in your `$env:path`, so you receiving an error.

It's kinda interesting what is this actual 'failing' username.
BTW, it's always recommended to use Latin letters to avoid such problems.

Here is the nice [article](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/) on how to add directory to the $env:path

Possible solutions:
1. Create new account with legal username.
2. Place directory with the scripts for decoding somewhere else (i.e. `C:\dirname`) and add it to $env:path

**Comment by Kcchouette** [comment] 2021-03-06 18:25
Hello

there is no need to do that to enable verbose, just go where Onionshare is installed (AppData\Local\Onionshare) and run:

> python/pythonw.exe -m onionshare --verbose

**Comment by mig5** [comment] 2021-05-04 02:16
Looks like a duplicate of #1023, as it has the same error message with 'utf-8' in the output.

**Closed by mig5** 2021-05-04 02:16 UTC
