### ISSUE TITLE
Custom description for receiver mode

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#733] opened 2018-08-23 03:10 UTC
Some users might fine it useful to display a custom description on the receiver mode onion page, this would allow the receiver to upload the requested files without having further contact with the receiver.
The description could be edited on the receiver mode screen or inside the setting screen.
<img width="1112" alt="screen shot 2018-08-22 at 8 02 42 pm" src="https://user-images.githubusercontent.com/10781882/44502653-542e2800-a647-11e8-95d6-8ccebf708127.png">

**Comment by mig5** [comment] 2019-03-11 05:43
Although this ticket is older, I'm inclined to mark it as duplicate of the newer #865 because there was a bit extra discussion over there, for what is the same feature request.

**Closed by mig5** 2019-03-11 05:43 UTC
Labels: enhancement
