### ISSUE TITLE
Onionshare shuts down unexpectedly on initiation of download > 2 Gb

### ISSUE THREAD

**Issue by connor992** [micahflee/onionshare#1095] opened 2020-03-08 22:21 UTC
HI Everyone,

I'm using onionshare 2.2 on a windows 7 64 install.  I've been playing around with sharing different filesizes, and I've noticed that as soon as someone tries to download from a shared URL via TOR, onionshare on the server end (where the file is being uploaded from) crashed as soon as the recipient clicks the "download files" button.

There's no error message of any kind,  onionshare simply closes and that's it.  

It successfully starts tranferring for files up to ~1.9gb no problem, btu as soon as the 2gb  boundary is crossed it crashes.

This is also the same if I try to share two files that total more than 2gb in size.

Has anyone else noticed this, and is there a work around for this behavior?

**Comment by rsnitsch** [comment] 2020-04-13 16:28
I can confirm this behavior. I have the same issue.

**Workaround:** ZIP your data into a set of splitted ZIPs, each volume being smaller than 2 GB. Then use the website mode of OnionShare to share the individual ZIP files. That should do the trick.

**Comment by connor992** [comment] 2020-04-13 21:15
> Workaround: ZIP your data into a set of splitted ZIPs, each volume being smaller than 2 GB. Then use the website mode of OnionShare to share the individual ZIP files. That should do the trick.
> 

Glad I wasn't the only one encountering this, thankyou for confirming!  I like the work around, thankyou!! :)

**Comment by mig5** [comment] 2020-05-28 03:14
Reproduced this on Linux. The trackback is:

```
34.5 MiB, 1.54%          Traceback (most recent call last):
  File "/home/user/git/onionshare/onionshare_gui/tab/tab.py", line 397, in timer_callback
    mode.handle_request_started(event)
  File "/home/user/git/onionshare/onionshare_gui/tab/mode/share_mode/__init__.py", line 295, in handle_request_started
    item = ShareHistoryItem(self.common, event["data"]["id"], filesize)
  File "/home/user/git/onionshare/onionshare_gui/tab/mode/history.py", line 122, in __init__
    self.progress_bar.setMaximum(total_bytes)
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
```

**Comment by mig5** [comment] 2020-05-28 03:23
Seems to be a Qt thing. This fix worked for me: https://github.com/lutraconsulting/qgis-mergin-plugin/issues/129

I've run into a separate bug, though, whereby the download stops at 1.1G (reported 'failed' in the browser)...

**Comment by ssempervirens** [comment] 2020-06-26 02:45
Just wanted to add I'm experiencing the same thing, and while the workaround of splitting it up works fine, definitely hoping this fix gets merged!

**Closed** 2020-07-05 18:48 UTC
Labels: bug

**Comment by connor992** [comment] 2020-07-10 02:40
Hi Guys, this sounds great, and seems like a work around has been found.  I'll readily admit I don't understand the lines of code that detail the fix.

For the laymen... is there an updated file I can download and place in my onionshare 2.2 install folder that will incorporate the fix?

Grateful for any guidance that can be offered :)
