### ISSUE TITLE
Transfer % and ETA Missing when sharing 2 or more folders concurrently

### ISSUE THREAD

**Issue by ASmith-** [micahflee/onionshare#363] opened 2017-02-24 05:02 UTC
I shared two folders concurrently on OnionShare v0.9.1 today and immediately noticed the Bytes size transferred, % of the total and ETA to finish were all missing values and entirely hidden. Nothing to indicate the Downloads were properly proceeding nor when they would finish up whatsoever.

I doubt this issue is patched in the new OnionShare v1.0.0 that was released 6hrs ago and I am anxious to install over the top of my previous and well used OnionShare utility and therefore rushed to point this out so the application issue can be patched and help make OnionShare even better.

Have you considered porting over a I2P version?

**Comment by mig5** [comment] 2017-05-21 04:02
By 'concurrently' do you mean that you started a share of 2x folders, or that you were downloading the share from 2 separate computers/browsers simutaneously?

I can't reproduce against the master branch when sharing 2 folders and downloading the slug from 2 separate computers simultaneously - both progress bars are showing accurate information.

<img width="418" alt="screen shot 2017-05-21 at 1 58 57 pm" src="https://cloud.githubusercontent.com/assets/99173/26281056/fb781f2c-3e2d-11e7-8ffd-aeee4dfe75e7.png">

i2p can be discussed in #377

**Comment by mig5** [comment] 2018-01-15 04:59
I still don't reproduce any issue viewing the progress of simultaneous downloads in current master branch so I'm going to close this out

![onionshare_simultaneous](https://user-images.githubusercontent.com/99173/34927790-b531beda-f9b0-11e7-96ee-23bb8cf53445.png)

**Closed by mig5** 2018-01-15 04:59 UTC
