### ISSUE TITLE
Command Line usage crashes on OS X

### ISSUE THREAD

**Issue by MacLemon** [micahflee/onionshare#239] opened 2015-12-11 23:18 UTC
This happens on system `python 2.7.5` on OS X 10.9.5 Mavericks:
```
$ /Applications/OnionShare.app/Contents/Resources/onionshare --help
Traceback (most recent call last):
  File "/Applications/OnionShare.app/Contents/Resources/onionshare", line 28, in <module>
    onionshare = zi.load_module('onionshare')
  File "onionshare/__init__.pyc", line 20, in <module>
  File "onionshare/onionshare.pyc", line 23, in <module>
ImportError: No module named stem.control
```

This happens on MacPorts `python 2.7.10` on OS X 10.10.5 Yosemite:
```
$ /Applications/OnionShare.app/Contents/Resources/onionshare --help
Traceback (most recent call last):
  File "/Applications/OnionShare.app/Contents/Resources/onionshare", line 28, in <module>
    onionshare = zi.load_module('onionshare')
  File "onionshare/__init__.pyc", line 20, in <module>
  File "onionshare/onionshare.pyc", line 22, in <module>
  File "onionshare/web.pyc", line 21, in <module>
ImportError: No module named flask
```

**Comment by MacLemon** [comment] 2015-12-11 23:38
Also on OS X 10.11.2 El Capitan with system `python 2.7.10`:
```
$ /Applications/OnionShare.app/Contents/Resources/onionshare
Traceback (most recent call last):
  File "/Applications/OnionShare.app/Contents/Resources/onionshare", line 28, in <module>
    onionshare = zi.load_module('onionshare')
  File "onionshare/__init__.pyc", line 20, in <module>
  File "onionshare/onionshare.pyc", line 23, in <module>
ImportError: No module named stem.control
```

**Comment by micahflee** [comment] 2015-12-14 23:20
This is a duplicate of #201. I think I have a solution -- would you mind checking my comment in the other issue and letting me know if it works?

**Closed** 2015-12-14 23:20 UTC
Labels: duplicate
