### ISSUE TITLE
Truncated files during download

### ISSUE THREAD

**Issue by pgerber** [micahflee/onionshare#1084] opened 2019-12-29 15:19 UTC
In OnionShare 2.2 as well as on the *develop* branch files downloaded are truncated.

## Steps to Reproduce:

Create a test file and and start serving it via OnionShare:

```
user@disp2491:~/src/onionshare$ dd if=/dev/zero of=test2 count=1 bs=1M
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.0061201 s, 171 MB/s
user@disp2491:~/src/onionshare$ dev_scripts/onionshare test
OnionShare 2.2 | https://onionshare.org/
Connecting to the Tor network: 100% - Done
Setting up onion service on port 17604.
Compressing files.
 * Running on http://127.0.0.1:17604/ (Press CTRL+C to quit)

Give this address to the recipient:
http://onionshare:mortally-sixtieth@pg5ztpgnnvwql3llml6kekfefncqorzh5rete24wgpesmfrg7jyefbad.onion

Press Ctrl+C to stop the server
127.0.0.1 - - [29/Dec/2019 16:06:49] "GET /download HTTP/1.1" 200 -
1.0 MiB, 100.00%            
Stopped because transfer is complete
```

Then download the file:

```
In [108]: url = 'http://onionshare:mortally-sixtieth@pg5ztpgnnvwql3llml6kekfefncqorzh5rete24wgpesmfrg7jyefbad.onio
     ...: n'

In [109]: resp = requests.get(url + '/download')

In [110]: len(resp.content)
Out[110]: 273566

In [111]: testdata = open('test', 'rb').read()

In [112]: len(testdata)
Out[112]: 1048576

In [113]: resp.content == testdata[:len(resp.content)]
Out[113]: True
```

The position at which the content is truncated varies. As far as I can tell OnionShare is shut down before the transfer is finished. As an experiment, I added a `time.sleep(30)` after requesting the shutdown in [share_mode.py:174](https://github.com/micahflee/onionshare/blob/72dc6df362fc5e1d9820a4936b2fa9514e4a4fad/onionshare/web/share_mode.py#L174). After that the content was transferred completely. Also this doesn't happen with `--stay-open`.

## Platform

OS: Debian 10 Buster running on top of Qubes OS 4.0
Packages:
```
$ dpkg -l python3-flask python3-stem python3-pyqt5 python3-crypto python3-socks python-nautilus tor obfs4proxy python3-pytest build-essential fakeroot python3-all python3-stdeb dh-python python3-flask-httpauth python3-distutils
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                   Version                Architecture Description
+++-======================-======================-============-===================================================
ii  build-essential        12.6                   amd64        Informational list of build-essential packages
ii  dh-python              3.20190308             all          Debian helper tools for packaging Python libraries 
ii  fakeroot               1.23-1                 amd64        tool for simulating superuser privileges
ii  obfs4proxy             0.0.7-4+b12            amd64        pluggable transport proxy for Tor, implementing obf
ii  python-nautilus        1.2.2-2                amd64        Python binding for Nautilus components
ii  python3-all            3.7.3-1                amd64        package depending on all supported Python 3 runtime
ii  python3-crypto         2.6.1-9+b1             amd64        cryptographic algorithms and protocols for Python 3
ii  python3-distutils      3.7.3-1                all          distutils package for Python 3.x
ii  python3-flask          1.0.2-3                all          micro web framework based on Werkzeug and Jinja2 - 
ii  python3-flask-httpauth 3.2.4-3                all          Basic and Digest HTTP authentication for Flask (Pyt
ii  python3-pyqt5          5.11.3+dfsg-1+b3       amd64        Python 3 bindings for Qt5
ii  python3-pytest         3.10.1-2               all          Simple, powerful testing in Python3
ii  python3-socks          1.6.8+dfsg-1           all          Python 3 SOCKS client module
ii  python3-stdeb          0.8.5-1                all          Python to Debian source package conversion plugins 
ii  python3-stem           1.7.1-1                all          Tor control library for Python 3 series
ii  tor                    0.4.2.5-1~d10.buster+1 amd64        anonymizing overlay network for TCP
```

**Comment by mig5** [comment] 2020-01-17 06:07
Thanks for the report. It sounds like a duplicate of #929

**Closed** 2020-05-27 23:53 UTC
