### ISSUE TITLE
Add an option to show the version

### ISSUE THREAD

**Issue by nielsk** [micahflee/onionshare#260] opened 2016-01-16 22:06 UTC
I installed onionshare via blackarch and arch and wanted to compare which version they actually install.
But there is no option to show the current version of onionshare.

**Comment by freddymartinez9** [comment] 2016-01-18 21:22
I would also like this. On Debian, I build it locally and installed 0.8.1 but if I do apt-cache show onionshare, it shows me two packages. 

I(nstalled locally)
Package: onionshare
Maintainer: Micah Lee <micah@micahflee.com>
Version: 0.8-1

(I suspect this one is from the tor repos)
Package: onionshare
Version: 0.6-3
Maintainer: Anonymity Tools Debian Maintainers <pkg-anonymity-tools@lists.alioth.debian.org>

**Comment by u451f** [comment] 2016-01-19 09:35
@freddymartinez9 onionshare is in Debian: https://tracker.debian.org/pkg/onionshare
You probably installed it from wheezy-backports.

**Comment by freddymartinez9** [comment] 2016-02-08 23:04
I don't use backports, it actually might be serving

>  0.6-3 from Section: contrib/net

but that's irrelevant to this issue. 

What would be good is to have the version queried from the build version and output the version using -v option in CLI _and_ to have the version in the onionshare GUI, maybe in dark gray text in the QT window, maybe in the bottom right.

**Comment by micahflee** [comment] 2016-02-12 17:24
Agree, this is a good idea. I'll mark this is a duplicate of #251 and use that issue.

**Closed** 2016-02-12 17:24 UTC
Labels: duplicate
