### ISSUE TITLE
Download & Upload files within OnionShare (Without Tor Browser)

### ISSUE THREAD

**Issue by trymeouteh** [micahflee/onionshare#1302] opened 2021-02-27 16:47 UTC
Please allow users to be able to download shared files within the OnionShare client and be able to upload received files within the OnionShare client and not need to download and install the Tor Browser to do so.

**Comment by micahflee** [comment] 2021-02-28 19:21
Related to #1295

**Comment by mig5** [comment] 2021-02-28 22:15
I think this is a duplicate of https://github.com/micahflee/onionshare/issues/365 (even though it really only talks about Share mode, but it is really the same request 'don't require Tor Browser to interact with OnionShare'

**Closed by mig5** 2021-02-28 22:15 UTC
