### ISSUE TITLE
Support command line version in OSX and Windows

### ISSUE THREAD

**Issue by mrphs** [micahflee/onionshare#201] opened 2015-06-08 01:02 UTC
Application quits unexpectedly right after launch on OSX 10.9.5. First I thought maybe it has an issue with the python version shipped with 10.9.5, then I tried to run it from terminal and:
```
Traceback (most recent call last):
  File "/usr/local/bin/onionshare", line 28, in <module>
    onionshare = zi.load_module('onionshare')
  File "onionshare/__init__.pyc", line 20, in <module>
  File "onionshare/onionshare.pyc", line 23, in <module>
ImportError: No module named stem.control
```

**Comment by remagio** [comment] 2015-06-08 14:39
Looks like PATH env isn't properly listed in the terminal session when launching onionshare. Happened sometimes, I installed stem by myself and checked $USER/.bash_profile for 2.7 & 3.4 paths

**Comment by whoisjake** [comment] 2015-10-30 13:58
Happens on 10.11.1 (El Captain) as well...

**Comment by micahflee** [comment] 2015-11-16 03:04
Hmm, I've used onionshare in El Captain and haven't run into this issue. I'll try to reproduce it though.

**Comment by micahflee** [comment] 2015-11-21 00:20
This is odd. I can't reproduce it in El Capitan. Does this happen just in the command line version, or do you get the crash in the GUI as well? Is your `/usr/local/bin/onionshare` a symlink to `/Applications/OnionShare.app/Contents/Resources/onionshare`?

**Comment by whoisjake** [comment] 2015-11-25 19:17
for myself, the GUI works fine... running the binary (either directly or through a symlink) gives the same error as pasted above.

I might be missing something as I didn't get any clear instructions on doing anything to my env... I'm not a python developer so if I need to modify my environment variables, that would be something that's not obvious to me. The README.md says nothing about needing any additional environment setup.

**Comment by micahflee** [comment] 2015-12-06 02:31
You shouldn't need to do anything special with your environment, running `/Applications/OnionShare.app/Contents/Resources/onionshare` should just work. I'm not sure what's going on, and I can't reproduce it. But I'm about to make a new release, version 0.8. When I do, you can try testing that version and let me know if it still doesn't work.

**Comment by mrphs** [comment] 2015-12-06 17:22
$ /Applications/OnionShare.app/Contents/Resources/onionshare
Traceback (most recent call last):
  File "/Applications/OnionShare.app/Contents/Resources/onionshare",
line 28, in <module>
    onionshare = zi.load_module('onionshare')
  File "onionshare/__init__.pyc", line 20, in <module>
  File "onionshare/onionshare.pyc", line 23, in <module>
ImportError: No module named stem.control

**Comment by whoisjake** [comment] 2015-12-10 14:56
So this *might* be the issue... I have python installed via homebrew...

```
$ /usr/bin/env python --version
Python 2.7.11
```

So it's not using the *system* Python... and after doing some rudimentary digging, not a python developer, couldn't find a "stem" package on the system Python either... Might be new to El Capitan Python?

When I did this:
```
$ pip install stem flask
```

Then onion share worked with Homebrew python...

**Comment by micahflee** [comment] 2015-12-11 18:24
@whoisjake you know I bet this is it. Should be easy enough to fix, I just need to patch the onionshare script to use the python bundled with onionshare. I'm at a conference now but I'll try it out soon.

**Comment by micahflee** [comment] 2015-12-14 23:19
The version of python that gets bundled with OnionShare is at `/Applications/OnionShare.app/Contents/MacOS/python`.

What happens when you run this?
`/Applications/OnionShare.app/Contents/MacOS/python /Applications/OnionShare.app/Contents/Resources/onionshare --help`

If that works like expected, then the patch is really simple. It's difficult for me to test myself without uninstalling python.org's python, etc.

**Comment by whoisjake** [comment] 2015-12-16 20:47
```
$ /Applications/OnionShare.app/Contents/MacOS/python --version
Python 2.7.9
```

```
$ /Applications/OnionShare.app/Contents/MacOS/python /Applications/OnionShare.app/Contents/Resources/onionshare --help
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
```

**Comment by micahflee** [comment] 2016-04-10 22:23
I'm switching from py2app to PyInstaller. Using the new system there doesn't seem to be an easy way to create a release with multiple executables in it. For now I'm going to just not support the command line version of OnionShare in OSX without git cloning the source code.

**Comment by micahflee** [comment] 2016-04-12 06:36
Actually, it looks like using [MERGE](https://pythonhosted.org/PyInstaller/#example-merge-spec-file) I can in fact support multiple executables. Since I'm making the Windows version use PyInstaller as well, I believe I can support a command line version for both OS X and Windows.

**Comment by micahflee** [comment] 2016-04-12 17:56
Actually, nevermind. The MERGE feature is broken in the current release of PyInstaller. This issue is blocked by https://github.com/pyinstaller/pyinstaller/issues/1527.

**Comment by micahflee** [comment] 2016-09-06 18:55
Thanks to #302, we're no longer using PyInstaller, and this is way simpler to do with cx_Freeze. It will be in the imminent release, 0.9.1.

**Closed** 2016-09-06 20:39 UTC
Labels: blocked, enhancement
