### ISSUE TITLE
Need to Replace HidServAuth Every Time?? Really?

### ISSUE THREAD

**Issue by ASmith-** [micahflee/onionshare#364] opened 2017-02-24 05:32 UTC
Need to Replace HidServAuth Every Time?? Really?

The Wiki on the Stealth Onion Service States 
"After you're done downloading the file being shared, you can remove the HidServAuth line from your torrc file again."

Why? It makes a great deal of sense to continue to use that hidden service authorization encrypted key, and optionally allow to create a new one if the user wanted at some point to carry-out. Meanwhile if the OnionShare user wanted to operate in a non-Stealth Hidden Service operation they could simply uncheck the Advanced Options for normal operation and keep the HidServAuth line in their torrc file intact if they wished. Previous peers with that HidservAuth line previously wouldn't need to continuously replace it over and over. How? Eliminate the slug words and use the same .onion link when running in a Stealth mode Hidden Service. Add a option to refresh this ( create a new .onion link and new HidServAuth line) users could use as and if they desired ).

Replacing the HidServAuth torrc line every time OnionShare is booted and files are shared with the Advanced Options -- Create Stealth Onion option enabled requires both the link provided securely but also the peer or peers to additionally add and delete the HidServAuth line on the torrc file on their end every time also. This awkward series of steps is going to diminish its overall use and detracts from its appeal.

**Comment by micahflee** [comment] 2017-02-25 21:51
The only way to make it so the HidServAuth string isn't different every time is to also retain the onion service key, so that OnionShare URL isn't different every time. So in this way, the feature you're asking for is kind of a duplicate of #295.

But also, I think this is reasonable default behavior. What if I want to send SECRET_FILE1 to PERSON1, and then later send SECRET_FILE2 to PERSON2. It would be bad if PERSON1 had the HidServAuth string that was only intended for PERSON2. If there's persistence in OnionShare at all, I think it needs to be very deliberate.

But also, I think this would be much easier if Tor Browser had a good UX for managing access to stealth onion services. Having to manually edit the torrc each time is terrible UX, but being able to click the onion icon and select "Stealth onion services" and then add/delete HidServAuth strings would be much nicer.

**Closed by micahflee** 2017-02-25 21:51 UTC
