### ISSUE TITLE
When the "You are running the latest version of OnionShare." message comes up and click on another app 

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#532] opened 2018-01-15 00:16 UTC
When the "You are running the latest version of OnionShare." message comes up and click on another app, the message will go behind the settings dialog and the settings dialog will have all the options disabled. Video showing the bug.
[bug.mov.zip](https://github.com/micahflee/onionshare/files/1629974/bug.mov.zip)

**Comment by mig5** [comment] 2018-01-15 00:40
Hmm. For me the dialog appears up front of the SettingsDialog.

Clicking OK re-enables the buttons in the SettingsDialog. That seems normal to me.

I'll keep trying to reproduce how to make it appear in the background somehow..

**Comment by mig5** [comment] 2018-01-15 00:49
Ah yes, I reproduced when I clicked on another app indeed. After that the alert dialog appears in the 'background' compared to Settings Dialog if you click back on the app with a mouse pointer. If you use Command-Tab to switch back to the OnionShare app instead of a mouse, the alert dialog appears in front again.

**Comment by mig5** [comment] 2018-01-23 02:48
I've been looking into this and I don't think we can fix it, at least as far as I can see. The SettingsDialog is a modal QDialog and this has something to do with it when it gets focus.

You can resolve it by clicking on the Alert dialog (yes you can see it, you just need to move the SettingsDialog out of the way) and even though it's still in the 'background' whilst it is focus,  you can Command-Tab away and back again, and it's in front again.

There appears no way to set the Alert (QMessageBox) to always retain focus from the QDialog, even if it is setModal(True) so I think we can just live with this minor quirk.

However this did lead me to the discovery that the Alert class does not setModal(True) and it should, because otherwise you can attempt to start a share while the 'OnionShare cannot connect to Tor' dialog is displayed over the main app. I'll open a separate PR for that. Meanwhile I suggest we #wontfix this.

**Comment by mig5** [comment] 2021-05-03 03:23
This actually seems fixed somehow these days, I can't reproduce the problem.

**Closed by mig5** 2021-05-03 03:23 UTC
Labels: bug, minor
