### ISSUE TITLE
Crash on Mac 0S X Sierra (10.12.6)

### ISSUE THREAD

**Issue by passereve** [micahflee/onionshare#927] opened 2019-02-27 22:20 UTC
passereve$ /Applications/OnionShare.app/Contents/MacOS/onionshare-gui --debug
OnionShare 2.0 | https://onionshare.org/
[fév 27 2019 23:16:10] Onion.__init__
[fév 27 2019 23:16:10] OnionShare.__init__
[fév 27 2019 23:16:10] OnionShareGui.__init__
[fév 27 2019 23:16:11] Web.__init__: is_gui=True, mode=share
[fév 27 2019 23:16:11] ShareModeWeb.__init__
[fév 27 2019 23:16:11] ShareMode.update_primary_action
[fév 27 2019 23:16:11] Web.__init__: is_gui=True, mode=receive
[fév 27 2019 23:16:11] ReceiveModeWeb.__init__
[fév 27 2019 23:16:11] TorConnectionDialog.__init__
[fév 27 2019 23:16:11] TorConnectionDialog.start
[fév 27 2019 23:16:11] TorConnectionThread.__init__
[fév 27 2019 23:16:11] TorConnectionThread.run
[fév 27 2019 23:16:11] Onion.connect
[fév 27 2019 23:16:11] Onion.connect: tor_data_directory=/Users/passereve/Library/Containers/com.micahflee.onionshare/Data/Library/Application Support/OnionShare/tmpsiru3uw4
2019-02-27 23:16:16.818 onionshare-gui[98232:2419604] Bartender: Loaded BartenderHelperTwoOneThree
Connexion au réseau Tor: 100% - Done
[fév 27 2019 23:16:26] Onion.connect: Connected to tor 0.3.5.7 (git-9beb085c10562a25)
[fév 27 2019 23:16:27] TorConnectionDialog._connected_to_tor
[fév 27 2019 23:16:27] UpdateThread.__init__
[fév 27 2019 23:16:27] UpdateThread.run
[fév 27 2019 23:16:27] UpdateChecker.__init__
[fév 27 2019 23:16:27] UpdateChecker.check: force=False
[fév 27 2019 23:16:27] Settings.__init__
[fév 27 2019 23:16:27] Settings.load
[fév 27 2019 23:16:27] UpdateChecker.check: checking for updates
[fév 27 2019 23:16:27] UpdateChecker.check: loading http://lldan5gahapx5k7iafb3s4ikijc4ni7gx5iywdflkba5y2ezyg6sjgyd.onion/latest-version.txt
[fév 27 2019 23:16:27] Onion.get_tor_socks_port
[fév 27 2019 23:16:32] UpdateChecker.check: latest OnionShare version: 2.0
[fév 27 2019 23:16:32] Settings.load
[fév 27 2019 23:16:32] Settings.save
[fév 27 2019 23:16:32] Settings.save: Settings saved in /Users/passereve/Library/Containers/com.micahflee.onionshare/Data/Library/Application Support/OnionShare/onionshare.json
[fév 27 2019 23:16:32] UpdateThread._update_not_available
2019-02-27 23:16:34.652 onionshare-gui[98232:2419604] unable to obtain configuration from file:///Library/Preferences/com.apple.ViewBridge.plist due to Error Domain=NSCocoaErrorDomain Code=257 "The file “com.apple.ViewBridge.plist” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/Library/Preferences/com.apple.ViewBridge.plist, NSUnderlyingError=0x7fc2453f2ea0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
2019-02-27 23:16:34.661 onionshare-gui[98232:2419604] warning: <NSRemoteView: 0x7fc2460825c0> determined it was necessary to configure <NSVBOpenPanel: 0x7fc2441e0850> to support remote view vibrancy
[fév 27 2019 23:16:48] ShareMode.update_primary_action
[fév 27 2019 23:16:51] Mode.start_server
[fév 27 2019 23:16:51] OnionShare.set_stealth: stealth=False
[fév 27 2019 23:16:51] Mode.start_server: Starting an onion thread
[fév 27 2019 23:16:51] OnionThread.__init__
[fév 27 2019 23:16:51] OnionThread.run
[fév 27 2019 23:16:51] WebThread.__init__
[fév 27 2019 23:16:51] WebThread.run
[fév 27 2019 23:16:51] Web.start: port=17650, stay_open=False, public_mode=False, persistent_slug=
[fév 27 2019 23:16:51] Web.generate_slug: persistent_slug=
[fév 27 2019 23:16:51] Web.generate_slug: built random slug: "waffle-appendage"
Traceback (most recent call last):
  File "site-packages/werkzeug/serving.py", line 75, in <module>
ModuleNotFoundError: No module named 'SocketServer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "onionshare_gui/threads.py", line 77, in run
  File "onionshare/web/web.py", line 255, in start
  File "site-packages/flask/app.py", line 940, in run
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "site-packages/werkzeug/serving.py", line 79, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "http/server.py", line 627, in <module>
  File "http/server.py", line 871, in SimpleHTTPRequestHandler
  File "mimetypes.py", line 355, in init
  File "mimetypes.py", line 204, in read
PermissionError: [Errno 1] Operation not permitted: '/usr/local/etc/mime.types'
Abort trap: 6

**Comment by mig5** [comment] 2019-10-19 04:20
```
File "site-packages/werkzeug/serving.py", line 75, in
ModuleNotFoundError: No module named 'SocketServer'
```

I can't reproduce that (though not on Sierra anymore) but presumably if there was a module missing from a core library like that in the OnionShare package, it would affect all OS X users... not sure how this could occur.

```
 PermissionError: [Errno 1] Operation not permitted: '/usr/local/etc/mime.types'
```

This one sounds like a duplicate of #1037  e.g other weird things happening on your computer that are interfering with normal functionality. (Or could it even be triggering the first error in the trackback and so explaining that too?)

**Closed by mig5** 2019-10-19 04:20 UTC
Labels: bug
