### ISSUE TITLE
GUI quits unexpectedly for large file on linux mint

### ISSUE THREAD

**Issue by Calibre720** [micahflee/onionshare#240] opened 2015-12-13 11:56 UTC
Command line works for the same file
GUI worked for small files
GUI quit unexpectedly without any error message on large file
(2.4 GB file on linux mint)

**Comment by micahflee** [comment] 2016-04-14 19:18
I haven't been able to reproduce this. In any case it seems like it's maybe a duplicate of #231

**Closed by micahflee** 2016-04-14 19:18 UTC
