### ISSUE TITLE
onionshare port 9151 tor port 9150

### ISSUE THREAD

**Issue by Mrkebubun** [micahflee/onionshare#214] opened 2015-10-08 21:30 UTC
im trying to use onionshare but it asking tor browser to restart everytime i try to share file.
and sometime messege pop up and asking about port and download tor browser kind of stuff.

for information:
i running onionshare on windows.

**Comment by Mrkebubun** [comment] 2015-10-08 21:31
Tor unexpectedly exited. This might be due to a bug in Tor itself, another program on your system, or faulty hardware. Until you restart Tor, the Tor Browser will not able to reach any websites. If the problem persists, please send a copy of your Tor Log to the support team.

Restarting Tor will not close your browser tabs.

this is the messege i got when try to share file.

**Comment by Mantechox** [comment] 2015-10-13 02:30
Do you know? I have exactly the same problem. I never thought that someone else did, because everyone seems to use it correctly.
The same error messages and everything, when I start OnionShare, without initiating Tor, tells me that (summarized) "Can not connect to the ports of Tor (9051, 9151.) Tor is working?". Starting first and then OnionShare Tor, Tor is restarted with the same message as you say, with two buttons "accept" or "reset" and for any 2, does not work OnionShare.
I thought it was enough to change the port that connects Tor (With the declining knowledge I have about it, changing the settings of the Firefox browser) but had no effect on that but of disconnect from the Internet. I really wish you can help us in a specific way and calmly (mostly because I do not know much about programming on these apps, even though I have a couple of years and maintaining privacy using them as high as possible).
I'm using Windows 10 64 bits
Tor folder is in desktop
mmm....What else?
Of course, thanks.

**Comment by Mrkebubun** [comment] 2015-10-13 12:40
im trying OnionShare 0.7 and its work,maybe there is a bug in new release 0.7.1
you can check this link
https://github.com/micahflee/onionshare/releases/

**Comment by Mantechox** [comment] 2015-10-13 13:42
It works for me to. Awesome! And thanks. Maybe this coulb be fixed in the future.

**Comment by freddymartinez9** [comment] 2015-10-14 02:30
but why is it closed? if it's introduced 0.7.1 this is a regression and still a bug, we can test it in a VM @micahflee I can work on this.

**Comment by micahflee** [comment] 2015-11-16 03:10
Looks like this is a duplicate of #101. Can you post in that other issue what version of Windows you're using?

**Closed by micahflee** 2015-11-16 03:10 UTC
