### ISSUE TITLE
persistent crash when starting a share

### ISSUE THREAD

**Issue by cfm** [micahflee/onionshare#1037] opened 2019-09-21 22:14 UTC
# Steps to reproduce

1. Open OnionShare 2.1, installed from `brew cask install onionshare`.
2. Add any file(s) to the "Share Files" tab.
3. Click **Start sharing**.

# Expected behavior

The share starts successfully.

# Actual behavior

Preamble of [full crash report](https://github.com/micahflee/onionshare/files/3639135/onionshare-crash.txt):

```
Process:               onionshare-gui [41143]
Path:                  /Applications/OnionShare.app/Contents/MacOS/onionshare-gui
Identifier:            com.micahflee.onionshare
Version:               2.1 (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           onionshare-gui [41143]
User ID:               501

Date/Time:             2019-09-21 15:11:51.500 -0700
OS Version:            Mac OS X 10.14.6 (18G95)
Report Version:        12
Anonymous UUID:        258599F7-4C35-523D-32E8-D810FD739898

Sleep/Wake UUID:       FFF069EB-E726-4FFB-8153-19C27147DCC2

Time Awake Since Boot: 580000 seconds
Time Since Wake:       2600 seconds

System Integrity Protection: disabled

Crashed Thread:        8  WebThread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
```

**Comment by micahflee** [comment] 2019-09-22 17:16
I'm not able to reproduce this in macOS 10.14.6, but it looks like it's the web thread that crashed. Can you open a terminal and run OnionShare like this?

```sh
/Applications/OnionShare.app/Contents/MacOS/onionshare-gui -v
```

Then make it crash again, and copy and paste the output from the terminal here.

**Comment by cfm** [comment] 2019-09-23 18:59
Thanks for taking a look, and my apologies for not including a verbose transcript right off.

```
Last login: Mon Sep 23 10:33:08 on ttys000
ozymandias:~ cfm$ /Applications/OnionShare.app/Contents/MacOS/onionshare-gui -v

OnionShare 2.1 | https://onionshare.org/
[Sep 23 2019 11:50:10] Onion.__init__
[Sep 23 2019 11:50:10] OnionShare.__init__
[Sep 23 2019 11:50:10] OnionShareGui.__init__
[Sep 23 2019 11:50:11] Settings.__init__
[Sep 23 2019 11:50:11] Settings.load
[Sep 23 2019 11:50:11] Settings.load: Trying to load /Users/cfm/Library/Containers/com.micahflee.onionshare/Data/Library/Application Support/OnionShare/onionshare.json
[Sep 23 2019 11:50:11] Web.__init__: is_gui=True, mode=share
[Sep 23 2019 11:50:11] ShareModeWeb.__init__
[Sep 23 2019 11:50:11] ShareMode.update_primary_action
[Sep 23 2019 11:50:11] Web.__init__: is_gui=True, mode=receive
[Sep 23 2019 11:50:11] ReceiveModeWeb.__init__
[Sep 23 2019 11:50:11] TorConnectionDialog.__init__
[Sep 23 2019 11:50:11] TorConnectionDialog.start
[Sep 23 2019 11:50:11] TorConnectionThread.__init__
[Sep 23 2019 11:50:11] TorConnectionThread.run
[Sep 23 2019 11:50:11] Onion.connect
[Sep 23 2019 11:50:11] Onion.connect: tor_data_directory=/Users/cfm/Library/Containers/com.micahflee.onionshare/Data/Library/Application Support/OnionShare/tmpai_oqxkd
2019-09-23 11:50:12.166 onionshare-gui[68014:25249842] unable to obtain configuration from file:///Library/Preferences/com.apple.ViewBridge.plist due to Error Domain=NSCocoaErrorDomain Code=257 "The file “com.apple.ViewBridge.plist” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/Library/Preferences/com.apple.ViewBridge.plist, NSUnderlyingError=0x7f88e9ccad90 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
Connecting to the Tor network: 15% - Establishing an encrypted directory connectConnecting to the Tor network: 45% - Asking for relay descriptors for internal pConnecting to the Tor network: 45% - Asking for relay descriptors for internal pConnecting to the Tor network: 45% - Asking for relay descriptors for internal pConnecting to the Tor network: 45% - Asking for relay descriptors for internal pConnecting to the Tor network: 45% - Asking for relay descriptors for internal pConnecting to the Tor network: 50% - Loading relay descriptors for internal pathConnecting to the Tor network: 50% - Loading relay descriptors for internal pathConnecting to the Tor network: 50% - Loading relay descriptors for internal pathConnecting to the Tor network: 50% - Loading relay descriptors for internal pathConnecting to the Tor network: 50% - Loading relay descriptors for internal pathConnecting to the Tor network: 50% - Loading relay descriptors for internal pathConnecting to the Tor network: 50% - Loading relay descriptors for internal pathConnecting to the Tor network: 100% - Done
[Sep 23 2019 11:50:20] Onion.connect: Connected to tor 0.3.5.8 (git-5030edfb534245ed)
[Sep 23 2019 11:50:20] TorConnectionDialog._connected_to_tor
[Sep 23 2019 11:50:20] UpdateThread.__init__
[Sep 23 2019 11:50:20] UpdateThread.run
[Sep 23 2019 11:50:20] UpdateChecker.__init__
[Sep 23 2019 11:50:20] UpdateChecker.check: force=False
[Sep 23 2019 11:50:20] Settings.__init__
[Sep 23 2019 11:50:20] Settings.load
[Sep 23 2019 11:50:20] Settings.load: Trying to load /Users/cfm/Library/Containers/com.micahflee.onionshare/Data/Library/Application Support/OnionShare/onionshare.json
[Sep 23 2019 11:50:20] UpdateChecker.check: checking for updates
[Sep 23 2019 11:50:20] UpdateChecker.check: loading http://lldan5gahapx5k7iafb3s4ikijc4ni7gx5iywdflkba5y2ezyg6sjgyd.onion/latest-version.txt
[Sep 23 2019 11:50:20] Onion.get_tor_socks_port
[Sep 23 2019 11:50:27] UpdateChecker.check: latest OnionShare version: 2.1
[Sep 23 2019 11:50:27] Settings.load
[Sep 23 2019 11:50:27] Settings.load: Trying to load /Users/cfm/Library/Containers/com.micahflee.onionshare/Data/Library/Application Support/OnionShare/onionshare.json
[Sep 23 2019 11:50:27] Settings.save
[Sep 23 2019 11:50:27] Settings.save: Settings saved in /Users/cfm/Library/Containers/com.micahflee.onionshare/Data/Library/Application Support/OnionShare/onionshare.json
[Sep 23 2019 11:50:27] UpdateThread._update_not_available
[Sep 23 2019 11:50:28] ShareMode.update_primary_action
[Sep 23 2019 11:50:33] Mode.start_server
[Sep 23 2019 11:50:33] OnionShare.set_stealth: stealth=False
[Sep 23 2019 11:50:33] Mode.start_server: Starting an onion thread
[Sep 23 2019 11:50:33] OnionThread.__init__
[Sep 23 2019 11:50:33] OnionThread.run
[Sep 23 2019 11:50:33] Web.generate_slug: persistent_slug=
[Sep 23 2019 11:50:33] Web.generate_slug: built random slug: "payment-cesspool"
[Sep 23 2019 11:50:33] OnionShare.start_onion_service
[Sep 23 2019 11:50:33] Onion.start_onion_service
Setting up onion service on port 17620.
[Sep 23 2019 11:50:33] Onion.start_onion_service: key_type=NEW, key_content=ED25519-V3
[Sep 23 2019 11:50:37] Settings.save
[Sep 23 2019 11:50:37] Settings.save: Settings saved in /Users/cfm/Library/Containers/com.micahflee.onionshare/Data/Library/Application Support/OnionShare/onionshare.json
[Sep 23 2019 11:50:37] WebThread.__init__
[Sep 23 2019 11:50:37] WebThread.run
[Sep 23 2019 11:50:37] Web.start: port=17620, stay_open=False, public_mode=False, slug=payment-cesspool
[Sep 23 2019 11:50:37] Mode.start_server_step2
[Sep 23 2019 11:50:37] CompressThread.__init__
[Sep 23 2019 11:50:37] CompressThread.run
[Sep 23 2019 11:50:37] ShareModeWeb.set_file_info
Traceback (most recent call last):
  File "onionshare_gui/threads.py", line 89, in run
  File "onionshare/web/web.py", line 256, in start
  File "flask/app.py", line 940, in run
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/user/code/onionshare/venv/lib/python3.7/site-packages/PyInstaller-3.4-py3.7.egg/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "werkzeug/serving.py", line 57, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/user/code/onionshare/venv/lib/python3.7/site-packages/PyInstaller-3.4-py3.7.egg/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "http/server.py", line 627, in <module>
  File "http/server.py", line 871, in SimpleHTTPRequestHandler
  File "mimetypes.py", line 355, in init
  File "mimetypes.py", line 204, in read
PermissionError: [Errno 1] Operation not permitted: '/usr/local/etc/mime.types'
Abort trap: 6
```

This looked like a Homebrew conflict—

```
ozymandias:~ cfm$ ls -al /usr/local/etc/mime.types
lrwxr-xr-x  1 cfm  admin  36 Feb 17  2019 /usr/local/etc/mime.types -> ../Cellar/mutt/1.11.3/etc/mime.types
ozymandias:~ cfm$ ls -al /usr/local/etc/../Cellar/mutt/1.11.3/etc/mime.types
-rw-r--r--  1 cfm  staff  3162 Feb  1  2019 /usr/local/etc/../Cellar/mutt/1.11.3/etc/mime.types
```

—and, sure enough, all's well after `brew uninstall mutt && brew cask reinstall onionshare`.  That's unfortunate, but I also concede that it's not a problem in OnionShare per se.

**Comment by mig5** [comment] 2019-10-19 04:07
I'm going to close this as as far as I can tell, it's indeed 'Not Our Bug' and not something we can avoid.. 

I don't know anything about homebrew but presumably this is bad practice for the mutt homebrew package to be clobbering a system-wide file such as /usr/local/etc/mime.types for its own purposes like this. I'd encourage you to report it to the relevant maintainer of that package. But thanks for digging into the root cause, it might help others!!

**Closed by mig5** 2019-10-19 04:07 UTC
Labels: bug
