### ISSUE TITLE
Possibility of sending only one file without converting it on a .zip file

### ISSUE THREAD

**Issue by emmapeel2** [micahflee/onionshare#663] opened 2018-03-06 15:54 UTC
I would like to use OnionShare more, to send images or text files to users, but many times people don't feel comfortable clicking on a zip onion link for security reasons. I would like to be able to send them the file without compressing it on a zip file.

It will be a bigger transaction, but in some cases it is not a problem. Or could be optional.

**Comment by Baccount** [comment] 2018-03-06 16:58
Duplicate of #653

**Comment by micahflee** [comment] 2018-03-06 19:09
This isn't actually a duplicate. #653 was requesting the ability to download each file individually. This issue is, if you're only sharing one file, don't zip it. If you're sharing multiple files, zip them like normal.

I think this is a fine thing to implement, so long as we can make sure both OnionShare and Tor Browser can do gzip compression on that file.

**Comment by micahflee** [comment] 2018-03-06 19:12
Potentially relevant:

https://github.com/closeio/Flask-gzip
https://github.com/libwilliam/flask-compress
http://flask.pocoo.org/snippets/122/

**Comment by Baccount** [comment] 2018-03-06 19:19
Thanks for the explanation @micahflee

**Comment by emmapeel2** [comment] 2018-03-06 20:35
Count me in for any testing!

**Comment by mig5** [comment] 2018-09-22 00:14
Fixed in https://github.com/micahflee/onionshare/pull/774 !

**Closed by mig5** 2018-09-22 00:14 UTC
Labels: enhancement

**Comment by jvoisin** [comment] 2022-05-21 18:19
Unfortunately, I'd like to share a 5G file with some friends, which is already heavily compressed. I don't want to have OnionShare compressing it again in gzip, nor do I want to uncompress it since its content is **huge**.
