### ISSUE TITLE
Option request

### ISSUE THREAD

**Issue by regressmods** [micahflee/onionshare#1103] opened 2020-04-01 15:34 UTC
Can you add a opiton not to cashe the www, since you have no cli for windows what makes no sence you can add this I seen it in many pyhon windows exe's have it, but I am sure you didn't add it for a reason and I can't keep installing everything to make my own point in downloaded something already made is I don't muck it up.

So yes can we have a option when we use the website opiton to we don't have to restart the tool every time we make a little change to the html fiile or any file for that matter your tool is cool just missing a few things like cli for windows, and option to be able to change things without casheing them also this isn't good on the system having your original copy and a copy the tool is using takes up ram or page file or where ever our hiding it.

This will enable users to make more dynamic websites with your tool without need of some php back end been able to monitor files or links with a simple cli tool this side (already done) on another platform so we can do forums and other tools.

Thanks bud great work tho, this tool as grown alot since I saw it last time it was just a basic share tool back then.

**Comment by kpcyrd** [comment] 2020-04-02 01:35
I think this a duplicate of #1059

**Comment by mig5** [comment] 2020-04-06 04:22
Indeed it is a duplicate, closing.

**Closed by mig5** 2020-04-06 04:22 UTC
