### ISSUE TITLE
OnionShare 2.1.dev1 still crashes on Mac OS Sierra

### ISSUE THREAD

**Issue by passereve** [micahflee/onionshare#971] opened 2019-04-23 10:52 UTC
wazo:~ passereve$ /Applications/OnionShare.app/Contents/MacOS/onionshare-gui
OnionShare 2.1.dev1 | https://onionshare.org/
2019-04-23 12:25:15.409 onionshare-gui[30874:1275827] Bartender: Loaded BartenderHelperTwoOneThree
Connecting to the Tor network: 100% - Done
2019-04-23 12:25:32.550 onionshare-gui[30874:1275827] unable to obtain configuration from file:///Library/Preferences/com.apple.ViewBridge.plist due to Error Domain=NSCocoaErrorDomain Code=257 "The file “com.apple.ViewBridge.plist” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/Library/Preferences/com.apple.ViewBridge.plist, NSUnderlyingError=0x7fe193fd3320 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
2019-04-23 12:25:32.558 onionshare-gui[30874:1275827] warning: <NSRemoteView: 0x7fe193fd6d40> determined it was necessary to configure <NSVBOpenPanel: 0x7fe193fc7d50> to support remote view vibrancy
Setting up onion service on port 17601.
Traceback (most recent call last):
  File "site-packages/werkzeug/serving.py", line 75, in <module>
ModuleNotFoundError: No module named 'SocketServer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "onionshare_gui/threads.py", line 89, in run
  File "onionshare/web/web.py", line 256, in start
  File "site-packages/flask/app.py", line 940, in run
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "site-packages/werkzeug/serving.py", line 79, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "http/server.py", line 627, in <module>
  File "http/server.py", line 871, in SimpleHTTPRequestHandler
  File "mimetypes.py", line 355, in init
  File "mimetypes.py", line 204, in read
PermissionError: [Errno 1] Operation not permitted: '/usr/local/etc/mime.types'
Abort trap: 6
wazo:~ passereve$

**Comment by mig5** [comment] 2019-04-29 21:29
So it's still a duplicate of #927 then :)

**Closed by mig5** 2019-04-29 21:29 UTC
