### ISSUE TITLE
Download onionshare links within the onionshare client

### ISSUE THREAD

**Issue by trymeouteh** [micahflee/onionshare#1041] opened 2019-09-30 23:55 UTC
Please allow users to download onionshare files within the onionshare client and not require the TOR browser. This will make it easy for people when you want to share files.

If you want to share a file with a friend, all you need to do is tell them to download the onionshare client and then you give them the link and your friend will use the link in onionshare and download the file. No TOR browser needed!

Most file sharing clients can allow you to share and receive files. Please allow onionshare to receive files.

**Comment by mig5** [comment] 2019-10-01 00:03
Duplicate of #365

**Closed by mig5** 2019-10-01 00:03 UTC

**Comment by trymeouteh** [comment] 2019-10-01 02:57
Receive mode is cool but a download mode will make this complete. The download mode should be a mode where you paste a onionshare URL and then it will show you the files in the link and you can click on Download to download the files onto your computer. No need to open the Tor browser and paste the link.
