### ISSUE TITLE
[UX] OnionShare Server - Internet Connection Messaging

### ISSUE THREAD

**Issue by huertanix** [micahflee/onionshare#370] opened 2017-03-10 01:43 UTC
_Adding [UX] to the title since there's no tag for it--I can change the title and add tag if one is created_

**Current design**

If internet connection is interrupted, changed, or lost, client can’t load page and server doesn’t explain why. Example in a trip between Washington D.C. and Boston on the Acela train:

1. Alice logs onto trash Amtrak wifi ready to share some dank memes.
2. Memes added, onion address is generated and all appears to be ok.
3. Bob cannot load .onion address in Tor Browser on their hella-fast and reliable home internet connection.
4. OnionShare Server UI doesn’t display indication of a problem.
5. Alice tries tethering to phone and using her expensive data plan. Alice can confirm she has internet access again by opening a browser and loading a web page.
6. Bob still cannot load .onion address in Tor Browser on their hella-fast and reliable home internet connection.
7. OnionShare Server UI doesn’t display indication of a problem.
8. Alice gets pinged by her mobile provider saying she will owe infinite money if she goes over her data plan with all this tethering.
9. Alice stops tethering and waits until the train reaches Wilmington, Delaware where Amtrak wifi starts working again.
10. Bob still cannot load .onion address in Tor Browser on their hella-fast and reliable home internet connection.
11. OnionShare Server UI doesn’t display indication of a problem.

**Requested design**

In the same scenario:

1. Alice logs onto trash Amtrak wifi ready to share some dank memes.
2. Memes added, onion address is generated but OnionShare indicates that that no one will be able to access files until the user is back online.
3. Alice tries tethering to phone and using her expensive data plan. Alice can confirm she has internet access again by opening a browser and loading a web page.
4. OnionShare Server detects new, working internet connection, re-configures things behind the scenes and indicates in the UI that it’s online and files can be accessed from the outside.
5. Alice disconnects because her mobile provider is literally Scrooge McDuck.
6. OnionShare indicates that that no one will be able to access files until the user is back online.
7. Alice reaches Wilmington, OnionShare Server detects new, working internet connection, re-configures things behind the scenes and indicates in the UI that it’s online and files can be accessed from the outside.
8. Bob downloads Alice’s dank memes:
9. ![tumblr_nnza8p6brr1ssnxmlo1_1280](https://cloud.githubusercontent.com/assets/72914/23778549/d5662ad0-0508-11e7-8d9b-cda51b4f8cfb.jpg)

**Comment by mig5** [comment] 2017-12-05 21:31
If I'm not mistaken, much of this is really a duplicate of #295 (for it to work, you'd have to re-start the Onion HS, and for any of this to make sense, the private key of the HS would have to be the same).

**Comment by mig5** [comment] 2018-01-15 05:02
I'm going to close this because the functionality is now all there to arrange a share under the same URL at different times:

1) #500 - stops a share and notifies when the Tor connection is lost
2) #485 - ability to use a persistent URL (re-use private key + slug)

**Closed by mig5** 2018-01-15 05:02 UTC
