### ISSUE TITLE
Multiple instances?

### ISSUE THREAD

**Issue by ghostlands** [micahflee/onionshare#656] opened 2018-03-01 04:49 UTC
Meditating on #653 the thought occurred to me that it might be useful to allow multiple instances. Both VLC and Winamp - for instance 9_9 - used to have options in the settings for allowing multiple instances..

It would get more complicated where persistent addresses are concerned; two onionshares with different persistent addresses would need to read two different JSONs. Something like my template in #485 which included exporting and importing keys would probably be required for this feature.

**Comment by mig5** [comment] 2018-03-01 05:14
I think this is kind of duplicate of a concept regarding 'self contained' OnionShare where it stores its config, Tor state data, and 'temporary directory' (for preparing the zip) all in the one place.

Because that's a complicated issue, it's kind of spread across several issues:

#506 - configurable or 'app contained' temp dir
#367 - 'no-install' version (or 'run onionshare self contained from a specific directory')
#366 - 'portable settings' (actually already resolved, really)
#551 - store Tor state data in a persistent dir e.g inside the contained Onionshare installation dir

So I am inclined to mark this as duplicate, but regarding the issue of different settings per instance, that's already solved: you can start OnionShare from the commandline with the ```--config```  arg, pointing at a custom (pre-prepared, but able to be edited via the OnionShare GUI Settings) json file.

I don't mean running OnionShare in cli mode, but you can start the onionshare-gui binary from the command line with the --config arg. In this way you can use an existing persistent key - you don't need a UI for 'exporting' or 'importing' it, just store it in the JSON as the 'private_key' variable, and OnionShare will use it.

But all in all, *yes* - a future version of Onionshare will run all its necessary components from within a specific, self-contained directory, and so you'll be able to run it in different locations on the same computer.

Another option: use QubesOS, with a separate VM per Onionshare :)

Hope that's clear!

**Comment by ghostlands** [comment] 2018-03-01 05:43
Yep. Wow, so this is kind of an umbrella bug :)

I just tested it! Very cool.

I'd still like to see the JSON settings thing someday get streamlined to an import/export. I'll have no problem using --config arguments, they're fun. But I'm thinking less technical users (journalists, sources, other Tails demographics) probably would need it to be more overt.

**Comment by mig5** [comment] 2018-03-01 08:33
Less technical users also less likely to need to be importing and exporting keys though too :)

**Comment by ghostlands** [comment] 2018-03-02 04:07
Journalists and whistleblowers can't be assumed to be technical users, and they both could have real need for that feature.

**Comment by ghostlands** [comment] 2018-03-02 04:11
Now #485. Is related. If I'd known multiple instances were possible before I might have foreseen this - sorry about that.

**Comment by mig5** [comment] 2018-03-02 04:32
I'm going to close this just because we have about 4 or 5 issues all dealing with tiny elements of the same fundamental piece of work, and adding more is just diluting the discussion in too many places at once.

To summarise, we are working on:

1) Ensuring the OnionShare installation directory will contain its config as well, and/or
2) Ensuring OnionShare installation can occur in multiple places, with configuration config location per instance
3) The 'temp' area where the zip file is created, may become configurable or more likely part of the 'self contained' instance directory where the config + actual app code is
4) The Tor state data will also go into that same config/app code area which also boosts performance and helps make Onionshare more 'portable' (e.g the whole thing could be on a USB stick)

**Closed by mig5** 2018-03-02 04:32 UTC
