### ISSUE TITLE
Unable to delete shared (temp?) data / Program unable to share data

### ISSUE THREAD

**Issue by Kimimaru-WSkD** [micahflee/onionshare#1375] opened 2021-06-04 18:56 UTC
Hello there! 
I tried to share some files but my 20, 25 GB on C: ran out (why is it not possible to install the progam where I want? For example on my 1TB SSD?) and OnionShare aborted with an error stating this (there is no space remaining on the disk) - I thought it would just share the data which I ALREADY have? Strange! 
Anyway, now my drive is FULL (0,5GB remaining) which means, that the system now came to a crawl because Windows has no room on the SSD anymore. Sadly I can not free the space which OnionShare "unsuccessfully blocked", why? The tab is cleared and I already restarted the machine. Also I found no folder where the data could be?

**Comment by Kimimaru-WSkD** [comment] 2021-06-04 19:15
I think I found the data (in the %TEMP% folder, is that right?), but the issue stands that it is not possible to share data when the program runs on C: and/or "compresses" the data. AGAIN (at least in my case) - it is already compressed/zipped. 
The program needs to share the data "as is" (at least as an option) or let the user install it on another drive (or at least its TEMP folder) otherwise it is just usable for some txt files. 
I think the idea (OnionShare) is great but not so good executed.

**Comment by mig5** [comment] 2021-06-05 01:34
Duplicate of #1328 / #1114 (the 'copying to temp is a problem for large shares' issue)

Duplicate of #367 (Ability to install somewhere else, on Windows)

**Closed by mig5** 2021-06-05 01:34 UTC
